### THIS IS AUTOGENERATED CODE
### Generated: 20200908 22:12:16
### Generated by: evtparsergen.py-d5d3b0b
### Generated from: https://github.com/microsoft/perfview/blob/P2.0.59/src/TraceEvent/Parsers/ASPNetTraceEventParser.man.xml

from ..utils import *

def get_AspNet_10000_op_code():
	return '1'

def read_AspNet_10000_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	ret['Method'] = read_win_type(buf, 'win:AnsiString')
	ret['Path'] = read_win_type(buf, 'win:AnsiString')
	ret['QueryString'] = read_win_type(buf, 'win:AnsiString')
	return ret

def get_AspNet_10001_op_code():
	return '2'

def read_AspNet_10001_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	return ret

def get_AspNet_10002_op_code():
	return '3'

def read_AspNet_10002_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	return ret

def get_AspNet_10003_op_code():
	return '4'

def read_AspNet_10003_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	return ret

def get_AspNet_10004_op_code():
	return '5'

def read_AspNet_10004_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	return ret

def get_AspNet_10005_op_code():
	return '6'

def read_AspNet_10005_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	return ret

def get_AspNet_10006_op_code():
	return '7'

def read_AspNet_10006_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	ret['DomainId'] = read_win_type(buf, 'win:UnicodeString')
	return ret

def get_AspNet_10007_op_code():
	return '8'

def read_AspNet_10007_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	ret['HandlerName'] = read_win_type(buf, 'win:UnicodeString')
	ret['EventName'] = read_win_type(buf, 'win:UnicodeString')
	return ret

def get_AspNet_10008_op_code():
	return '9'

def read_AspNet_10008_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	return ret

def get_AspNet_10009_op_code():
	return '10'

def read_AspNet_10009_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	ret['ModuleName'] = read_win_type(buf, 'win:UnicodeString')
	return ret

def get_AspNet_10010_op_code():
	return '11'

def read_AspNet_10010_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	ret['ModuleName'] = read_win_type(buf, 'win:UnicodeString')
	return ret

def get_AspNet_10011_op_code():
	return '12'

def read_AspNet_10011_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	return ret

def get_AspNet_10012_op_code():
	return '13'

def read_AspNet_10012_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	return ret

def get_AspNet_10013_op_code():
	return '14'

def read_AspNet_10013_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	return ret

def get_AspNet_10014_op_code():
	return '15'

def read_AspNet_10014_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	return ret

def get_AspNet_10015_op_code():
	return '16'

def read_AspNet_10015_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	return ret

def get_AspNet_10016_op_code():
	return '17'

def read_AspNet_10016_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	ret['Files'] = read_win_type(buf, 'win:UnicodeString')
	ret['Status'] = read_win_type(buf, 'win:UnicodeString')
	return ret

def get_AspNet_10017_op_code():
	return '18'

def read_AspNet_10017_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	return ret

def get_AspNet_10018_op_code():
	return '19'

def read_AspNet_10018_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	return ret

def get_AspNet_10019_op_code():
	return '20'

def read_AspNet_10019_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	ret['ResolverType'] = read_win_type(buf, 'win:UnicodeString')
	ret['SessionId'] = read_win_type(buf, 'win:UnicodeString')
	return ret

def get_AspNet_10020_op_code():
	return '21'

def read_AspNet_10020_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	ret['ResolverResult'] = read_win_type(buf, 'win:UnicodeString')
	return ret

def get_AspNet_10021_op_code():
	return '22'

def read_AspNet_10021_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	return ret

def get_AspNet_10022_op_code():
	return '23'

def read_AspNet_10022_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	return ret

def get_AspNet_10023_op_code():
	return '24'

def read_AspNet_10023_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	return ret

def get_AspNet_10024_op_code():
	return '25'

def read_AspNet_10024_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	return ret

def get_AspNet_10025_op_code():
	return '26'

def read_AspNet_10025_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	return ret

def get_AspNet_10026_op_code():
	return '27'

def read_AspNet_10026_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	return ret

def get_AspNet_10027_op_code():
	return '28'

def read_AspNet_10027_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	return ret

def get_AspNet_10028_op_code():
	return '29'

def read_AspNet_10028_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	return ret

def get_AspNet_10029_op_code():
	return '30'

def read_AspNet_10029_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	return ret

def get_AspNet_10030_op_code():
	return '31'

def read_AspNet_10030_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	return ret

def get_AspNet_10031_op_code():
	return '32'

def read_AspNet_10031_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	return ret

def get_AspNet_10032_op_code():
	return '33'

def read_AspNet_10032_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	return ret

def get_AspNet_10033_op_code():
	return '34'

def read_AspNet_10033_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	return ret

def get_AspNet_10034_op_code():
	return '35'

def read_AspNet_10034_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	return ret

def get_AspNet_10035_op_code():
	return '36'

def read_AspNet_10035_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	return ret

def get_AspNet_10036_op_code():
	return '37'

def read_AspNet_10036_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	return ret

def get_AspNet_10037_op_code():
	return '38'

def read_AspNet_10037_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	return ret

def get_AspNet_10038_op_code():
	return '39'

def read_AspNet_10038_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	return ret

def get_AspNet_10039_op_code():
	return '40'

def read_AspNet_10039_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	return ret

def get_AspNet_10040_op_code():
	return '41'

def read_AspNet_10040_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	return ret

def get_AspNet_10041_op_code():
	return '42'

def read_AspNet_10041_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	return ret

def get_AspNet_10042_op_code():
	return '43'

def read_AspNet_10042_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	return ret

def get_AspNet_10043_op_code():
	return '44'

def read_AspNet_10043_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	return ret

def get_AspNet_10044_op_code():
	return '45'

def read_AspNet_10044_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	ret['User'] = read_win_type(buf, 'win:UnicodeString')
	return ret

def get_AspNet_10045_op_code():
	return '46'

def read_AspNet_10045_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	ret['Provider'] = read_win_type(buf, 'win:UnicodeString')
	ret['User'] = read_win_type(buf, 'win:UnicodeString')
	ret['Role'] = read_win_type(buf, 'win:UnicodeString')
	ret['Status'] = read_win_type(buf, 'win:UnicodeString')
	return ret

def get_AspNet_10046_op_code():
	return '47'

def read_AspNet_10046_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	ret['Provider'] = read_win_type(buf, 'win:UnicodeString')
	ret['User'] = read_win_type(buf, 'win:UnicodeString')
	ret['Roles'] = read_win_type(buf, 'win:UnicodeString')
	return ret

def get_AspNet_10047_op_code():
	return '48'

def read_AspNet_10047_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	return ret

def get_AspNet_10048_op_code():
	return '49'

def read_AspNet_10048_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	ret['Provider'] = read_win_type(buf, 'win:UnicodeString')
	ret['User'] = read_win_type(buf, 'win:UnicodeString')
	return ret

def get_AspNet_10049_op_code():
	return '50'

def read_AspNet_10049_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	ret['EventClassName'] = read_win_type(buf, 'win:UnicodeString')
	ret['EventCode'] = read_win_type(buf, 'win:UnicodeString')
	ret['EventDetailCode'] = read_win_type(buf, 'win:UnicodeString')
	return ret

def get_AspNet_10050_op_code():
	return '51'

def read_AspNet_10050_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	return ret

def get_AspNet_10051_op_code():
	return '52'

def read_AspNet_10051_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	ret['ProviderName'] = read_win_type(buf, 'win:UnicodeString')
	ret['RuleName'] = read_win_type(buf, 'win:UnicodeString')
	ret['EventGroupName'] = read_win_type(buf, 'win:UnicodeString')
	return ret

def get_AspNet_10052_op_code():
	return '53'

def read_AspNet_10052_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	return ret

def get_AspNet_10053_op_code():
	return '59'

def read_AspNet_10053_payload(buf):
	ret = {}
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	ret['Uri'] = read_win_type(buf, 'win:UnicodeString')
	ret['TraceWarningMsg'] = read_win_type(buf, 'win:UnicodeString')
	return ret

def get_AspNet_10054_op_code():
	return '60'

def read_AspNet_10054_payload(buf):
	ret = {}
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	ret['Uri'] = read_win_type(buf, 'win:UnicodeString')
	ret['TraceWriteMsg'] = read_win_type(buf, 'win:UnicodeString')
	return ret

def get_AspNet_10055_op_code():
	return '61'

def read_AspNet_10055_payload(buf):
	ret = {}
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	ret['Uri'] = read_win_type(buf, 'win:UnicodeString')
	ret['TraceWriteMsg'] = read_win_type(buf, 'win:UnicodeString')
	return ret

def get_AspNet_10056_op_code():
	return '62'

def read_AspNet_10056_payload(buf):
	ret = {}
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	ret['Uri'] = read_win_type(buf, 'win:UnicodeString')
	ret['TraceWriteMsg'] = read_win_type(buf, 'win:UnicodeString')
	return ret

def get_AspNet_10057_op_code():
	return '63'

def read_AspNet_10057_payload(buf):
	ret = {}
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	ret['Uri'] = read_win_type(buf, 'win:UnicodeString')
	ret['TraceWriteMsg'] = read_win_type(buf, 'win:UnicodeString')
	return ret

def get_AspNet_10058_op_code():
	return '64'

def read_AspNet_10058_payload(buf):
	ret = {}
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	ret['Uri'] = read_win_type(buf, 'win:UnicodeString')
	ret['TraceWriteMsg'] = read_win_type(buf, 'win:UnicodeString')
	return ret

def get_AspNet_10059_op_code():
	return '65'

def read_AspNet_10059_payload(buf):
	ret = {}
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	ret['Uri'] = read_win_type(buf, 'win:UnicodeString')
	ret['TraceWriteMsg'] = read_win_type(buf, 'win:UnicodeString')
	return ret

def get_AspNet_10060_op_code():
	return '66'

def read_AspNet_10060_payload(buf):
	ret = {}
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	ret['Uri'] = read_win_type(buf, 'win:UnicodeString')
	ret['TraceWriteMsg'] = read_win_type(buf, 'win:UnicodeString')
	return ret

def get_AspNet_10061_op_code():
	return '67'

def read_AspNet_10061_payload(buf):
	ret = {}
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	ret['Uri'] = read_win_type(buf, 'win:UnicodeString')
	ret['TraceWriteMsg'] = read_win_type(buf, 'win:UnicodeString')
	return ret

def get_AspNet_10062_op_code():
	return '68'

def read_AspNet_10062_payload(buf):
	ret = {}
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	ret['Uri'] = read_win_type(buf, 'win:UnicodeString')
	ret['TraceWriteMsg'] = read_win_type(buf, 'win:UnicodeString')
	return ret

def get_AspNet_10063_op_code():
	return '69'

def read_AspNet_10063_payload(buf):
	ret = {}
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	ret['Uri'] = read_win_type(buf, 'win:UnicodeString')
	ret['TraceWriteMsg'] = read_win_type(buf, 'win:UnicodeString')
	return ret

def get_AspNet_10064_op_code():
	return '70'

def read_AspNet_10064_payload(buf):
	ret = {}
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	ret['Uri'] = read_win_type(buf, 'win:UnicodeString')
	ret['TraceWriteMsg'] = read_win_type(buf, 'win:UnicodeString')
	return ret

