### THIS IS AUTOGENERATED CODE
### Generated: 20200908 22:12:23
### Generated by: evtparsergen.py-d5d3b0b
### Generated from: https://github.com/microsoft/perfview/blob/P2.0.59/src/TraceEvent/Parsers/kerneltraceeventparser.man.xml

from ..utils import *

def get_MSNT_SystemTrace_100000_op_code():
	return '0'

def read_MSNT_SystemTrace_100000_payload(buf):
	ret = {}
	ret['BufferSize'] = read_win_type(buf, 'win:UInt32')
	ret['Version'] = read_win_type(buf, 'win:UInt32')
	ret['ProviderVersion'] = read_win_type(buf, 'win:UInt32')
	ret['NumberOfProcessors'] = read_win_type(buf, 'win:UInt32')
	ret['EndTime'] = read_win_type(buf, 'win:UInt64')
	ret['TimerResolution'] = read_win_type(buf, 'win:UInt32')
	ret['MaxFileSize'] = read_win_type(buf, 'win:UInt32')
	ret['LogFileMode'] = read_win_type(buf, 'win:UInt32')
	ret['BuffersWritten'] = read_win_type(buf, 'win:UInt32')
	ret['StartBuffers'] = read_win_type(buf, 'win:UInt32')
	ret['PointerSize'] = read_win_type(buf, 'win:UInt32')
	ret['EventsLost'] = read_win_type(buf, 'win:UInt32')
	ret['CPUSpeed'] = read_win_type(buf, 'win:UInt32')
	ret['LoggerName'] = read_win_type(buf, 'win:Pointer')
	ret['LogFileName'] = read_win_type(buf, 'win:Pointer')
	ret['TimeZoneInformation'] = read_win_type(buf, 'win:UInt8')
	ret['BootTime'] = read_win_type(buf, 'win:UInt64')
	ret['PerfFreq'] = read_win_type(buf, 'win:UInt64')
	ret['StartTime'] = read_win_type(buf, 'win:UInt64')
	ret['ReservedFlags'] = read_win_type(buf, 'win:UInt32')
	ret['BuffersLost'] = read_win_type(buf, 'win:UInt32')
	ret['SessionNameString'] = read_win_type(buf, 'win:UnicodeString')
	ret['LogFileNameString'] = read_win_type(buf, 'win:UnicodeString')
	return ret

def get_MSNT_SystemTrace_100001_op_code():
	return '5'

def read_MSNT_SystemTrace_100001_payload(buf):
	ret = {}
	ret['GroupMask1'] = read_win_type(buf, 'win:UInt32')
	ret['GroupMask2'] = read_win_type(buf, 'win:UInt32')
	ret['GroupMask3'] = read_win_type(buf, 'win:UInt32')
	ret['GroupMask4'] = read_win_type(buf, 'win:UInt32')
	ret['GroupMask5'] = read_win_type(buf, 'win:UInt32')
	ret['GroupMask6'] = read_win_type(buf, 'win:UInt32')
	ret['GroupMask7'] = read_win_type(buf, 'win:UInt32')
	ret['GroupMask8'] = read_win_type(buf, 'win:UInt32')
	ret['KernelEventVersion'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100002_op_code():
	return '32'

def read_MSNT_SystemTrace_100002_payload(buf):
	ret = {}
	ret['GroupMask1'] = read_win_type(buf, 'win:UInt32')
	ret['GroupMask2'] = read_win_type(buf, 'win:UInt32')
	ret['GroupMask3'] = read_win_type(buf, 'win:UInt32')
	ret['GroupMask4'] = read_win_type(buf, 'win:UInt32')
	ret['GroupMask5'] = read_win_type(buf, 'win:UInt32')
	ret['GroupMask6'] = read_win_type(buf, 'win:UInt32')
	ret['GroupMask7'] = read_win_type(buf, 'win:UInt32')
	ret['GroupMask8'] = read_win_type(buf, 'win:UInt32')
	ret['KernelEventVersion'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100003_op_code():
	return '8'

def read_MSNT_SystemTrace_100003_payload(buf):
	ret = {}
	return ret

def get_MSNT_SystemTrace_100004_op_code():
	return '1'

def read_MSNT_SystemTrace_100004_payload(buf):
	ret = {}
	ret['UniqueProcessKey'] = read_win_type(buf, 'win:Pointer')
	ret['ProcessId'] = read_win_type(buf, 'win:UInt32')
	ret['ParentId'] = read_win_type(buf, 'win:UInt32')
	ret['SessionId'] = read_win_type(buf, 'win:UInt32')
	ret['ExitStatus'] = read_win_type(buf, 'win:Int32')
	ret['UserSID'] = read_win_type(buf, 'trace:WBEMSid')
	ret['ImageFileName'] = read_win_type(buf, 'win:AnsiString')
	ret['CommandLine'] = read_win_type(buf, 'win:UnicodeString')
	return ret

def get_MSNT_SystemTrace_100005_op_code():
	return '2'

def read_MSNT_SystemTrace_100005_payload(buf):
	ret = {}
	ret['UniqueProcessKey'] = read_win_type(buf, 'win:Pointer')
	ret['ProcessId'] = read_win_type(buf, 'win:UInt32')
	ret['ParentId'] = read_win_type(buf, 'win:UInt32')
	ret['SessionId'] = read_win_type(buf, 'win:UInt32')
	ret['ExitStatus'] = read_win_type(buf, 'win:Int32')
	ret['UserSID'] = read_win_type(buf, 'trace:WBEMSid')
	ret['ImageFileName'] = read_win_type(buf, 'win:AnsiString')
	ret['CommandLine'] = read_win_type(buf, 'win:UnicodeString')
	return ret

def get_MSNT_SystemTrace_100006_op_code():
	return '3'

def read_MSNT_SystemTrace_100006_payload(buf):
	ret = {}
	ret['UniqueProcessKey'] = read_win_type(buf, 'win:Pointer')
	ret['ProcessId'] = read_win_type(buf, 'win:UInt32')
	ret['ParentId'] = read_win_type(buf, 'win:UInt32')
	ret['SessionId'] = read_win_type(buf, 'win:UInt32')
	ret['ExitStatus'] = read_win_type(buf, 'win:Int32')
	ret['UserSID'] = read_win_type(buf, 'trace:WBEMSid')
	ret['ImageFileName'] = read_win_type(buf, 'win:AnsiString')
	ret['CommandLine'] = read_win_type(buf, 'win:UnicodeString')
	return ret

def get_MSNT_SystemTrace_100007_op_code():
	return '4'

def read_MSNT_SystemTrace_100007_payload(buf):
	ret = {}
	ret['UniqueProcessKey'] = read_win_type(buf, 'win:Pointer')
	ret['ProcessId'] = read_win_type(buf, 'win:UInt32')
	ret['ParentId'] = read_win_type(buf, 'win:UInt32')
	ret['SessionId'] = read_win_type(buf, 'win:UInt32')
	ret['ExitStatus'] = read_win_type(buf, 'win:Int32')
	ret['UserSID'] = read_win_type(buf, 'trace:WBEMSid')
	ret['ImageFileName'] = read_win_type(buf, 'win:AnsiString')
	ret['CommandLine'] = read_win_type(buf, 'win:UnicodeString')
	return ret

def get_MSNT_SystemTrace_100008_op_code():
	return '39'

def read_MSNT_SystemTrace_100008_payload(buf):
	ret = {}
	ret['UniqueProcessKey'] = read_win_type(buf, 'win:Pointer')
	ret['ProcessId'] = read_win_type(buf, 'win:UInt32')
	ret['ParentId'] = read_win_type(buf, 'win:UInt32')
	ret['SessionId'] = read_win_type(buf, 'win:UInt32')
	ret['ExitStatus'] = read_win_type(buf, 'win:Int32')
	ret['UserSID'] = read_win_type(buf, 'trace:WBEMSid')
	ret['ImageFileName'] = read_win_type(buf, 'win:AnsiString')
	ret['CommandLine'] = read_win_type(buf, 'win:UnicodeString')
	return ret

def get_MSNT_SystemTrace_100009_op_code():
	return '32'

def read_MSNT_SystemTrace_100009_payload(buf):
	ret = {}
	ret['ProcessId'] = read_win_type(buf, 'win:UInt32')
	ret['PageFaultCount'] = read_win_type(buf, 'win:UInt32')
	ret['HandleCount'] = read_win_type(buf, 'win:UInt32')
	ret['Reserved'] = read_win_type(buf, 'win:UInt32')
	ret['PeakVirtualSize'] = read_win_type(buf, 'trace:SizeT')
	ret['PeakWorkingSetSize'] = read_win_type(buf, 'trace:SizeT')
	ret['PeakPagefileUsage'] = read_win_type(buf, 'trace:SizeT')
	ret['QuotaPeakPagedPoolUsage'] = read_win_type(buf, 'trace:SizeT')
	ret['QuotaPeakNonPagedPoolUsage'] = read_win_type(buf, 'trace:SizeT')
	ret['VirtualSize'] = read_win_type(buf, 'trace:SizeT')
	ret['WorkingSetSize'] = read_win_type(buf, 'trace:SizeT')
	ret['PagefileUsage'] = read_win_type(buf, 'trace:SizeT')
	ret['QuotaPagedPoolUsage'] = read_win_type(buf, 'trace:SizeT')
	ret['QuotaNonPagedPoolUsage'] = read_win_type(buf, 'trace:SizeT')
	ret['PrivatePageCount'] = read_win_type(buf, 'trace:SizeT')
	return ret

def get_MSNT_SystemTrace_100010_op_code():
	return '33'

def read_MSNT_SystemTrace_100010_payload(buf):
	ret = {}
	ret['ProcessId'] = read_win_type(buf, 'win:UInt32')
	ret['PageFaultCount'] = read_win_type(buf, 'win:UInt32')
	ret['HandleCount'] = read_win_type(buf, 'win:UInt32')
	ret['Reserved'] = read_win_type(buf, 'win:UInt32')
	ret['PeakVirtualSize'] = read_win_type(buf, 'trace:SizeT')
	ret['PeakWorkingSetSize'] = read_win_type(buf, 'trace:SizeT')
	ret['PeakPagefileUsage'] = read_win_type(buf, 'trace:SizeT')
	ret['QuotaPeakPagedPoolUsage'] = read_win_type(buf, 'trace:SizeT')
	ret['QuotaPeakNonPagedPoolUsage'] = read_win_type(buf, 'trace:SizeT')
	ret['VirtualSize'] = read_win_type(buf, 'trace:SizeT')
	ret['WorkingSetSize'] = read_win_type(buf, 'trace:SizeT')
	ret['PagefileUsage'] = read_win_type(buf, 'trace:SizeT')
	ret['QuotaPagedPoolUsage'] = read_win_type(buf, 'trace:SizeT')
	ret['QuotaNonPagedPoolUsage'] = read_win_type(buf, 'trace:SizeT')
	ret['PrivatePageCount'] = read_win_type(buf, 'trace:SizeT')
	return ret

def get_MSNT_SystemTrace_100011_op_code():
	return '1'

def read_MSNT_SystemTrace_100011_payload(buf):
	ret = {}
	ret['ProcessId'] = read_win_type(buf, 'win:UInt32')
	ret['TThreadId'] = read_win_type(buf, 'win:UInt32')
	ret['StackBase'] = read_win_type(buf, 'win:Pointer')
	ret['StackLimit'] = read_win_type(buf, 'win:Pointer')
	ret['UserStackBase'] = read_win_type(buf, 'win:Pointer')
	ret['UserStackLimit'] = read_win_type(buf, 'win:Pointer')
	ret['StartAddr'] = read_win_type(buf, 'win:Pointer')
	ret['Win32StartAddr'] = read_win_type(buf, 'win:Pointer')
	ret['TebBase'] = read_win_type(buf, 'win:Pointer')
	ret['SubProcessTag'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100012_op_code():
	return '2'

def read_MSNT_SystemTrace_100012_payload(buf):
	ret = {}
	ret['ProcessId'] = read_win_type(buf, 'win:UInt32')
	ret['TThreadId'] = read_win_type(buf, 'win:UInt32')
	ret['StackBase'] = read_win_type(buf, 'win:Pointer')
	ret['StackLimit'] = read_win_type(buf, 'win:Pointer')
	ret['UserStackBase'] = read_win_type(buf, 'win:Pointer')
	ret['UserStackLimit'] = read_win_type(buf, 'win:Pointer')
	ret['StartAddr'] = read_win_type(buf, 'win:Pointer')
	ret['Win32StartAddr'] = read_win_type(buf, 'win:Pointer')
	ret['TebBase'] = read_win_type(buf, 'win:Pointer')
	ret['SubProcessTag'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100013_op_code():
	return '3'

def read_MSNT_SystemTrace_100013_payload(buf):
	ret = {}
	ret['ProcessId'] = read_win_type(buf, 'win:UInt32')
	ret['TThreadId'] = read_win_type(buf, 'win:UInt32')
	ret['StackBase'] = read_win_type(buf, 'win:Pointer')
	ret['StackLimit'] = read_win_type(buf, 'win:Pointer')
	ret['UserStackBase'] = read_win_type(buf, 'win:Pointer')
	ret['UserStackLimit'] = read_win_type(buf, 'win:Pointer')
	ret['StartAddr'] = read_win_type(buf, 'win:Pointer')
	ret['Win32StartAddr'] = read_win_type(buf, 'win:Pointer')
	ret['TebBase'] = read_win_type(buf, 'win:Pointer')
	ret['SubProcessTag'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100014_op_code():
	return '4'

def read_MSNT_SystemTrace_100014_payload(buf):
	ret = {}
	ret['ProcessId'] = read_win_type(buf, 'win:UInt32')
	ret['TThreadId'] = read_win_type(buf, 'win:UInt32')
	ret['StackBase'] = read_win_type(buf, 'win:Pointer')
	ret['StackLimit'] = read_win_type(buf, 'win:Pointer')
	ret['UserStackBase'] = read_win_type(buf, 'win:Pointer')
	ret['UserStackLimit'] = read_win_type(buf, 'win:Pointer')
	ret['StartAddr'] = read_win_type(buf, 'win:Pointer')
	ret['Win32StartAddr'] = read_win_type(buf, 'win:Pointer')
	ret['TebBase'] = read_win_type(buf, 'win:Pointer')
	ret['SubProcessTag'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100015_op_code():
	return '36'

def read_MSNT_SystemTrace_100015_payload(buf):
	ret = {}
	ret['NewThreadId'] = read_win_type(buf, 'win:UInt32')
	ret['OldThreadId'] = read_win_type(buf, 'win:UInt32')
	ret['NewThreadPriority'] = read_win_type(buf, 'win:Int8')
	ret['OldThreadPriority'] = read_win_type(buf, 'win:Int8')
	ret['PreviousCState'] = read_win_type(buf, 'win:UInt8')
	ret['SpareByte'] = read_win_type(buf, 'win:Int8')
	ret['OldThreadWaitReason'] = read_win_type(buf, 'win:Int8')
	ret['OldThreadWaitMode'] = read_win_type(buf, 'win:Int8')
	ret['OldThreadState'] = read_win_type(buf, 'win:Int8')
	ret['OldThreadWaitIdealProcessor'] = read_win_type(buf, 'win:Int8')
	ret['NewThreadWaitTime'] = read_win_type(buf, 'win:UInt32')
	ret['Reserved'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100016_op_code():
	return '37'

def read_MSNT_SystemTrace_100016_payload(buf):
	ret = {}
	return ret

def get_MSNT_SystemTrace_100017_op_code():
	return '57'

def read_MSNT_SystemTrace_100017_payload(buf):
	ret = {}
	ret['TThreadId'] = read_win_type(buf, 'win:UInt32')
	ret['StartTime'] = read_win_type(buf, 'win:UInt64')
	ret['ThreadRoutine'] = read_win_type(buf, 'win:Pointer')
	return ret

def get_MSNT_SystemTrace_100018_op_code():
	return '48'

def read_MSNT_SystemTrace_100018_payload(buf):
	ret = {}
	ret['Reserve'] = read_win_type(buf, 'win:Pointer')
	ret['Period'] = read_win_type(buf, 'win:UInt32')
	ret['Budget'] = read_win_type(buf, 'win:UInt32')
	ret['ObjectFlags'] = read_win_type(buf, 'win:UInt32')
	ret['Processor'] = read_win_type(buf, 'win:Int8')
	return ret

def get_MSNT_SystemTrace_100019_op_code():
	return '49'

def read_MSNT_SystemTrace_100019_payload(buf):
	ret = {}
	ret['Reserve'] = read_win_type(buf, 'win:Pointer')
	return ret

def get_MSNT_SystemTrace_100020_op_code():
	return '52'

def read_MSNT_SystemTrace_100020_payload(buf):
	ret = {}
	ret['Reserve'] = read_win_type(buf, 'win:Pointer')
	ret['TThreadId'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100021_op_code():
	return '53'

def read_MSNT_SystemTrace_100021_payload(buf):
	ret = {}
	ret['Reserve'] = read_win_type(buf, 'win:Pointer')
	ret['TThreadId'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100022_op_code():
	return '54'

def read_MSNT_SystemTrace_100022_payload(buf):
	ret = {}
	ret['Reserve'] = read_win_type(buf, 'win:Pointer')
	ret['DispatchState'] = read_win_type(buf, 'win:Int8')
	ret['Replenished'] = read_win_type(buf, 'win:Boolean')
	return ret

def get_MSNT_SystemTrace_100023_op_code():
	return '55'

def read_MSNT_SystemTrace_100023_payload(buf):
	ret = {}
	ret['Reserve'] = read_win_type(buf, 'win:Pointer')
	ret['Period'] = read_win_type(buf, 'win:UInt32')
	ret['Budget'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100024_op_code():
	return '56'

def read_MSNT_SystemTrace_100024_payload(buf):
	ret = {}
	ret['Reserve'] = read_win_type(buf, 'win:Pointer')
	ret['LateCountIncrement'] = read_win_type(buf, 'win:Int32')
	return ret

def get_MSNT_SystemTrace_100025_op_code():
	return '10'

def read_MSNT_SystemTrace_100025_payload(buf):
	ret = {}
	ret['DiskNumber'] = read_win_type(buf, 'win:UInt32')
	ret['IrpFlags'] = read_win_type(buf, 'win:UInt32')
	ret['TransferSize'] = read_win_type(buf, 'win:UInt32')
	ret['Reserved'] = read_win_type(buf, 'win:UInt32')
	ret['ByteOffset'] = read_win_type(buf, 'win:UInt64')
	ret['FileObject'] = read_win_type(buf, 'win:Pointer')
	ret['Irp'] = read_win_type(buf, 'win:Pointer')
	ret['HighResResponseTime'] = read_win_type(buf, 'win:UInt64')
	return ret

def get_MSNT_SystemTrace_100026_op_code():
	return '11'

def read_MSNT_SystemTrace_100026_payload(buf):
	ret = {}
	ret['DiskNumber'] = read_win_type(buf, 'win:UInt32')
	ret['IrpFlags'] = read_win_type(buf, 'win:UInt32')
	ret['TransferSize'] = read_win_type(buf, 'win:UInt32')
	ret['Reserved'] = read_win_type(buf, 'win:UInt32')
	ret['ByteOffset'] = read_win_type(buf, 'win:UInt64')
	ret['FileObject'] = read_win_type(buf, 'win:Pointer')
	ret['Irp'] = read_win_type(buf, 'win:Pointer')
	ret['HighResResponseTime'] = read_win_type(buf, 'win:UInt64')
	return ret

def get_MSNT_SystemTrace_100027_op_code():
	return '12'

def read_MSNT_SystemTrace_100027_payload(buf):
	ret = {}
	ret['Irp'] = read_win_type(buf, 'win:Pointer')
	return ret

def get_MSNT_SystemTrace_100028_op_code():
	return '13'

def read_MSNT_SystemTrace_100028_payload(buf):
	ret = {}
	ret['Irp'] = read_win_type(buf, 'win:Pointer')
	return ret

def get_MSNT_SystemTrace_100029_op_code():
	return '15'

def read_MSNT_SystemTrace_100029_payload(buf):
	ret = {}
	ret['Irp'] = read_win_type(buf, 'win:Pointer')
	return ret

def get_MSNT_SystemTrace_100030_op_code():
	return '14'

def read_MSNT_SystemTrace_100030_payload(buf):
	ret = {}
	ret['DiskNumber'] = read_win_type(buf, 'win:UInt32')
	ret['IrpFlags'] = read_win_type(buf, 'win:UInt32')
	ret['HighResResponseTime'] = read_win_type(buf, 'win:UInt64')
	ret['Irp'] = read_win_type(buf, 'win:Pointer')
	return ret

def get_MSNT_SystemTrace_100031_op_code():
	return '34'

def read_MSNT_SystemTrace_100031_payload(buf):
	ret = {}
	ret['MajorFunction'] = read_win_type(buf, 'win:UInt32')
	ret['MinorFunction'] = read_win_type(buf, 'win:UInt32')
	ret['RoutineAddr'] = read_win_type(buf, 'win:Pointer')
	ret['FileObject'] = read_win_type(buf, 'win:Pointer')
	ret['Irp'] = read_win_type(buf, 'win:Pointer')
	ret['UniqMatchId'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100032_op_code():
	return '35'

def read_MSNT_SystemTrace_100032_payload(buf):
	ret = {}
	ret['Irp'] = read_win_type(buf, 'win:Pointer')
	ret['UniqMatchId'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100033_op_code():
	return '37'

def read_MSNT_SystemTrace_100033_payload(buf):
	ret = {}
	ret['Routine'] = read_win_type(buf, 'win:Pointer')
	ret['IrpPtr'] = read_win_type(buf, 'win:Pointer')
	ret['UniqMatchId'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100034_op_code():
	return '52'

def read_MSNT_SystemTrace_100034_payload(buf):
	ret = {}
	ret['RoutineAddr'] = read_win_type(buf, 'win:Pointer')
	ret['Irp'] = read_win_type(buf, 'win:Pointer')
	ret['UniqMatchId'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100035_op_code():
	return '53'

def read_MSNT_SystemTrace_100035_payload(buf):
	ret = {}
	ret['Irp'] = read_win_type(buf, 'win:Pointer')
	ret['UniqMatchId'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100036_op_code():
	return '10'

def read_MSNT_SystemTrace_100036_payload(buf):
	ret = {}
	ret['InitialTime'] = read_win_type(buf, 'win:Int64')
	ret['Status'] = read_win_type(buf, 'win:UInt32')
	ret['Index'] = read_win_type(buf, 'win:UInt32')
	ret['KeyHandle'] = read_win_type(buf, 'win:Pointer')
	ret['KeyName'] = read_win_type(buf, 'win:UnicodeString')
	return ret

def get_MSNT_SystemTrace_100037_op_code():
	return '11'

def read_MSNT_SystemTrace_100037_payload(buf):
	ret = {}
	ret['InitialTime'] = read_win_type(buf, 'win:Int64')
	ret['Status'] = read_win_type(buf, 'win:UInt32')
	ret['Index'] = read_win_type(buf, 'win:UInt32')
	ret['KeyHandle'] = read_win_type(buf, 'win:Pointer')
	ret['KeyName'] = read_win_type(buf, 'win:UnicodeString')
	return ret

def get_MSNT_SystemTrace_100038_op_code():
	return '12'

def read_MSNT_SystemTrace_100038_payload(buf):
	ret = {}
	ret['InitialTime'] = read_win_type(buf, 'win:Int64')
	ret['Status'] = read_win_type(buf, 'win:UInt32')
	ret['Index'] = read_win_type(buf, 'win:UInt32')
	ret['KeyHandle'] = read_win_type(buf, 'win:Pointer')
	ret['KeyName'] = read_win_type(buf, 'win:UnicodeString')
	return ret

def get_MSNT_SystemTrace_100039_op_code():
	return '13'

def read_MSNT_SystemTrace_100039_payload(buf):
	ret = {}
	ret['InitialTime'] = read_win_type(buf, 'win:Int64')
	ret['Status'] = read_win_type(buf, 'win:UInt32')
	ret['Index'] = read_win_type(buf, 'win:UInt32')
	ret['KeyHandle'] = read_win_type(buf, 'win:Pointer')
	ret['KeyName'] = read_win_type(buf, 'win:UnicodeString')
	return ret

def get_MSNT_SystemTrace_100040_op_code():
	return '14'

def read_MSNT_SystemTrace_100040_payload(buf):
	ret = {}
	ret['InitialTime'] = read_win_type(buf, 'win:Int64')
	ret['Status'] = read_win_type(buf, 'win:UInt32')
	ret['Index'] = read_win_type(buf, 'win:UInt32')
	ret['KeyHandle'] = read_win_type(buf, 'win:Pointer')
	ret['KeyName'] = read_win_type(buf, 'win:UnicodeString')
	return ret

def get_MSNT_SystemTrace_100041_op_code():
	return '15'

def read_MSNT_SystemTrace_100041_payload(buf):
	ret = {}
	ret['InitialTime'] = read_win_type(buf, 'win:Int64')
	ret['Status'] = read_win_type(buf, 'win:UInt32')
	ret['Index'] = read_win_type(buf, 'win:UInt32')
	ret['KeyHandle'] = read_win_type(buf, 'win:Pointer')
	ret['KeyName'] = read_win_type(buf, 'win:UnicodeString')
	return ret

def get_MSNT_SystemTrace_100042_op_code():
	return '16'

def read_MSNT_SystemTrace_100042_payload(buf):
	ret = {}
	ret['InitialTime'] = read_win_type(buf, 'win:Int64')
	ret['Status'] = read_win_type(buf, 'win:UInt32')
	ret['Index'] = read_win_type(buf, 'win:UInt32')
	ret['KeyHandle'] = read_win_type(buf, 'win:Pointer')
	ret['KeyName'] = read_win_type(buf, 'win:UnicodeString')
	return ret

def get_MSNT_SystemTrace_100043_op_code():
	return '17'

def read_MSNT_SystemTrace_100043_payload(buf):
	ret = {}
	ret['InitialTime'] = read_win_type(buf, 'win:Int64')
	ret['Status'] = read_win_type(buf, 'win:UInt32')
	ret['Index'] = read_win_type(buf, 'win:UInt32')
	ret['KeyHandle'] = read_win_type(buf, 'win:Pointer')
	ret['KeyName'] = read_win_type(buf, 'win:UnicodeString')
	return ret

def get_MSNT_SystemTrace_100044_op_code():
	return '18'

def read_MSNT_SystemTrace_100044_payload(buf):
	ret = {}
	ret['InitialTime'] = read_win_type(buf, 'win:Int64')
	ret['Status'] = read_win_type(buf, 'win:UInt32')
	ret['Index'] = read_win_type(buf, 'win:UInt32')
	ret['KeyHandle'] = read_win_type(buf, 'win:Pointer')
	ret['KeyName'] = read_win_type(buf, 'win:UnicodeString')
	return ret

def get_MSNT_SystemTrace_100045_op_code():
	return '19'

def read_MSNT_SystemTrace_100045_payload(buf):
	ret = {}
	ret['InitialTime'] = read_win_type(buf, 'win:Int64')
	ret['Status'] = read_win_type(buf, 'win:UInt32')
	ret['Index'] = read_win_type(buf, 'win:UInt32')
	ret['KeyHandle'] = read_win_type(buf, 'win:Pointer')
	ret['KeyName'] = read_win_type(buf, 'win:UnicodeString')
	return ret

def get_MSNT_SystemTrace_100046_op_code():
	return '20'

def read_MSNT_SystemTrace_100046_payload(buf):
	ret = {}
	ret['InitialTime'] = read_win_type(buf, 'win:Int64')
	ret['Status'] = read_win_type(buf, 'win:UInt32')
	ret['Index'] = read_win_type(buf, 'win:UInt32')
	ret['KeyHandle'] = read_win_type(buf, 'win:Pointer')
	ret['KeyName'] = read_win_type(buf, 'win:UnicodeString')
	return ret

def get_MSNT_SystemTrace_100047_op_code():
	return '21'

def read_MSNT_SystemTrace_100047_payload(buf):
	ret = {}
	ret['InitialTime'] = read_win_type(buf, 'win:Int64')
	ret['Status'] = read_win_type(buf, 'win:UInt32')
	ret['Index'] = read_win_type(buf, 'win:UInt32')
	ret['KeyHandle'] = read_win_type(buf, 'win:Pointer')
	ret['KeyName'] = read_win_type(buf, 'win:UnicodeString')
	return ret

def get_MSNT_SystemTrace_100048_op_code():
	return '22'

def read_MSNT_SystemTrace_100048_payload(buf):
	ret = {}
	ret['Status'] = read_win_type(buf, 'win:Pointer')
	ret['KeyHandle'] = read_win_type(buf, 'win:Pointer')
	ret['ElapsedTime'] = read_win_type(buf, 'win:Int64')
	ret['Index'] = read_win_type(buf, 'win:UInt32')
	ret['KeyName'] = read_win_type(buf, 'win:UnicodeString')
	return ret

def get_MSNT_SystemTrace_100049_op_code():
	return '22'

def read_MSNT_SystemTrace_100049_payload(buf):
	ret = {}
	ret['InitialTime'] = read_win_type(buf, 'win:Int64')
	ret['Status'] = read_win_type(buf, 'win:UInt32')
	ret['Index'] = read_win_type(buf, 'win:UInt32')
	ret['KeyHandle'] = read_win_type(buf, 'win:Pointer')
	ret['KeyName'] = read_win_type(buf, 'win:UnicodeString')
	return ret

def get_MSNT_SystemTrace_100050_op_code():
	return '23'

def read_MSNT_SystemTrace_100050_payload(buf):
	ret = {}
	ret['InitialTime'] = read_win_type(buf, 'win:Int64')
	ret['Status'] = read_win_type(buf, 'win:UInt32')
	ret['Index'] = read_win_type(buf, 'win:UInt32')
	ret['KeyHandle'] = read_win_type(buf, 'win:Pointer')
	ret['KeyName'] = read_win_type(buf, 'win:UnicodeString')
	return ret

def get_MSNT_SystemTrace_100051_op_code():
	return '24'

def read_MSNT_SystemTrace_100051_payload(buf):
	ret = {}
	ret['InitialTime'] = read_win_type(buf, 'win:Int64')
	ret['Status'] = read_win_type(buf, 'win:UInt32')
	ret['Index'] = read_win_type(buf, 'win:UInt32')
	ret['KeyHandle'] = read_win_type(buf, 'win:Pointer')
	ret['KeyName'] = read_win_type(buf, 'win:UnicodeString')
	return ret

def get_MSNT_SystemTrace_100052_op_code():
	return '25'

def read_MSNT_SystemTrace_100052_payload(buf):
	ret = {}
	ret['InitialTime'] = read_win_type(buf, 'win:Int64')
	ret['Status'] = read_win_type(buf, 'win:UInt32')
	ret['Index'] = read_win_type(buf, 'win:UInt32')
	ret['KeyHandle'] = read_win_type(buf, 'win:Pointer')
	ret['KeyName'] = read_win_type(buf, 'win:UnicodeString')
	return ret

def get_MSNT_SystemTrace_100053_op_code():
	return '26'

def read_MSNT_SystemTrace_100053_payload(buf):
	ret = {}
	ret['InitialTime'] = read_win_type(buf, 'win:Int64')
	ret['Status'] = read_win_type(buf, 'win:UInt32')
	ret['Index'] = read_win_type(buf, 'win:UInt32')
	ret['KeyHandle'] = read_win_type(buf, 'win:Pointer')
	ret['KeyName'] = read_win_type(buf, 'win:UnicodeString')
	return ret

def get_MSNT_SystemTrace_100054_op_code():
	return '27'

def read_MSNT_SystemTrace_100054_payload(buf):
	ret = {}
	ret['InitialTime'] = read_win_type(buf, 'win:Int64')
	ret['Status'] = read_win_type(buf, 'win:UInt32')
	ret['Index'] = read_win_type(buf, 'win:UInt32')
	ret['KeyHandle'] = read_win_type(buf, 'win:Pointer')
	ret['KeyName'] = read_win_type(buf, 'win:UnicodeString')
	return ret

def get_MSNT_SystemTrace_100055_op_code():
	return '32'

def read_MSNT_SystemTrace_100055_payload(buf):
	ret = {}
	ret['ParentIrp'] = read_win_type(buf, 'win:Pointer')
	ret['ChildIrp'] = read_win_type(buf, 'win:Pointer')
	return ret

def get_MSNT_SystemTrace_100056_op_code():
	return '0'

def read_MSNT_SystemTrace_100056_payload(buf):
	ret = {}
	ret['FileObject'] = read_win_type(buf, 'win:Pointer')
	ret['FileName'] = read_win_type(buf, 'win:UnicodeString')
	return ret

def get_MSNT_SystemTrace_100057_op_code():
	return '32'

def read_MSNT_SystemTrace_100057_payload(buf):
	ret = {}
	ret['FileObject'] = read_win_type(buf, 'win:Pointer')
	ret['FileName'] = read_win_type(buf, 'win:UnicodeString')
	return ret

def get_MSNT_SystemTrace_100058_op_code():
	return '35'

def read_MSNT_SystemTrace_100058_payload(buf):
	ret = {}
	ret['FileObject'] = read_win_type(buf, 'win:Pointer')
	ret['FileName'] = read_win_type(buf, 'win:UnicodeString')
	return ret

def get_MSNT_SystemTrace_100059_op_code():
	return '36'

def read_MSNT_SystemTrace_100059_payload(buf):
	ret = {}
	ret['FileObject'] = read_win_type(buf, 'win:Pointer')
	ret['FileName'] = read_win_type(buf, 'win:UnicodeString')
	return ret

def get_MSNT_SystemTrace_100060_op_code():
	return '64'

def read_MSNT_SystemTrace_100060_payload(buf):
	ret = {}
	ret['IrpPtr'] = read_win_type(buf, 'win:Pointer')
	ret['TTID'] = read_win_type(buf, 'win:Pointer')
	ret['FileObject'] = read_win_type(buf, 'win:Pointer')
	ret['CreateOptions'] = read_win_type(buf, 'win:UInt32')
	ret['FileAttributes'] = read_win_type(buf, 'win:UInt32')
	ret['ShareAccess'] = read_win_type(buf, 'win:UInt32')
	ret['OpenPath'] = read_win_type(buf, 'win:UnicodeString')
	return ret

def get_MSNT_SystemTrace_100061_op_code():
	return '65'

def read_MSNT_SystemTrace_100061_payload(buf):
	ret = {}
	ret['IrpPtr'] = read_win_type(buf, 'win:Pointer')
	ret['TTID'] = read_win_type(buf, 'win:Pointer')
	ret['FileObject'] = read_win_type(buf, 'win:Pointer')
	ret['FileKey'] = read_win_type(buf, 'win:Pointer')
	return ret

def get_MSNT_SystemTrace_100062_op_code():
	return '66'

def read_MSNT_SystemTrace_100062_payload(buf):
	ret = {}
	ret['IrpPtr'] = read_win_type(buf, 'win:Pointer')
	ret['TTID'] = read_win_type(buf, 'win:Pointer')
	ret['FileObject'] = read_win_type(buf, 'win:Pointer')
	ret['FileKey'] = read_win_type(buf, 'win:Pointer')
	return ret

def get_MSNT_SystemTrace_100063_op_code():
	return '73'

def read_MSNT_SystemTrace_100063_payload(buf):
	ret = {}
	ret['IrpPtr'] = read_win_type(buf, 'win:Pointer')
	ret['TTID'] = read_win_type(buf, 'win:Pointer')
	ret['FileObject'] = read_win_type(buf, 'win:Pointer')
	ret['FileKey'] = read_win_type(buf, 'win:Pointer')
	return ret

def get_MSNT_SystemTrace_100064_op_code():
	return '67'

def read_MSNT_SystemTrace_100064_payload(buf):
	ret = {}
	ret['Offset'] = read_win_type(buf, 'win:UInt64')
	ret['IrpPtr'] = read_win_type(buf, 'win:Pointer')
	ret['TTID'] = read_win_type(buf, 'win:Pointer')
	ret['FileObject'] = read_win_type(buf, 'win:Pointer')
	ret['FileKey'] = read_win_type(buf, 'win:Pointer')
	ret['IoSize'] = read_win_type(buf, 'win:UInt32')
	ret['IoFlags'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100065_op_code():
	return '68'

def read_MSNT_SystemTrace_100065_payload(buf):
	ret = {}
	ret['Offset'] = read_win_type(buf, 'win:UInt64')
	ret['IrpPtr'] = read_win_type(buf, 'win:Pointer')
	ret['TTID'] = read_win_type(buf, 'win:Pointer')
	ret['FileObject'] = read_win_type(buf, 'win:Pointer')
	ret['FileKey'] = read_win_type(buf, 'win:Pointer')
	ret['IoSize'] = read_win_type(buf, 'win:UInt32')
	ret['IoFlags'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100066_op_code():
	return '69'

def read_MSNT_SystemTrace_100066_payload(buf):
	ret = {}
	ret['IrpPtr'] = read_win_type(buf, 'win:Pointer')
	ret['TTID'] = read_win_type(buf, 'win:Pointer')
	ret['FileObject'] = read_win_type(buf, 'win:Pointer')
	ret['FileKey'] = read_win_type(buf, 'win:Pointer')
	ret['ExtraInfo'] = read_win_type(buf, 'win:Pointer')
	ret['InfoClass'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100067_op_code():
	return '70'

def read_MSNT_SystemTrace_100067_payload(buf):
	ret = {}
	ret['IrpPtr'] = read_win_type(buf, 'win:Pointer')
	ret['TTID'] = read_win_type(buf, 'win:Pointer')
	ret['FileObject'] = read_win_type(buf, 'win:Pointer')
	ret['FileKey'] = read_win_type(buf, 'win:Pointer')
	ret['ExtraInfo'] = read_win_type(buf, 'win:Pointer')
	ret['InfoClass'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100068_op_code():
	return '71'

def read_MSNT_SystemTrace_100068_payload(buf):
	ret = {}
	ret['IrpPtr'] = read_win_type(buf, 'win:Pointer')
	ret['TTID'] = read_win_type(buf, 'win:Pointer')
	ret['FileObject'] = read_win_type(buf, 'win:Pointer')
	ret['FileKey'] = read_win_type(buf, 'win:Pointer')
	ret['ExtraInfo'] = read_win_type(buf, 'win:Pointer')
	ret['InfoClass'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100069_op_code():
	return '74'

def read_MSNT_SystemTrace_100069_payload(buf):
	ret = {}
	ret['IrpPtr'] = read_win_type(buf, 'win:Pointer')
	ret['TTID'] = read_win_type(buf, 'win:Pointer')
	ret['FileObject'] = read_win_type(buf, 'win:Pointer')
	ret['FileKey'] = read_win_type(buf, 'win:Pointer')
	ret['ExtraInfo'] = read_win_type(buf, 'win:Pointer')
	ret['InfoClass'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100070_op_code():
	return '75'

def read_MSNT_SystemTrace_100070_payload(buf):
	ret = {}
	ret['IrpPtr'] = read_win_type(buf, 'win:Pointer')
	ret['TTID'] = read_win_type(buf, 'win:Pointer')
	ret['FileObject'] = read_win_type(buf, 'win:Pointer')
	ret['FileKey'] = read_win_type(buf, 'win:Pointer')
	ret['ExtraInfo'] = read_win_type(buf, 'win:Pointer')
	ret['InfoClass'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100071_op_code():
	return '72'

def read_MSNT_SystemTrace_100071_payload(buf):
	ret = {}
	ret['IrpPtr'] = read_win_type(buf, 'win:Pointer')
	ret['TTID'] = read_win_type(buf, 'win:Pointer')
	ret['FileObject'] = read_win_type(buf, 'win:Pointer')
	ret['FileKey'] = read_win_type(buf, 'win:Pointer')
	ret['Length'] = read_win_type(buf, 'win:UInt32')
	ret['InfoClass'] = read_win_type(buf, 'win:UInt32')
	ret['FileIndex'] = read_win_type(buf, 'win:UInt32')
	ret['FileName'] = read_win_type(buf, 'win:UnicodeString')
	return ret

def get_MSNT_SystemTrace_100072_op_code():
	return '77'

def read_MSNT_SystemTrace_100072_payload(buf):
	ret = {}
	ret['IrpPtr'] = read_win_type(buf, 'win:Pointer')
	ret['TTID'] = read_win_type(buf, 'win:Pointer')
	ret['FileObject'] = read_win_type(buf, 'win:Pointer')
	ret['FileKey'] = read_win_type(buf, 'win:Pointer')
	ret['Length'] = read_win_type(buf, 'win:UInt32')
	ret['InfoClass'] = read_win_type(buf, 'win:UInt32')
	ret['FileIndex'] = read_win_type(buf, 'win:UInt32')
	ret['FileName'] = read_win_type(buf, 'win:UnicodeString')
	return ret

def get_MSNT_SystemTrace_100073_op_code():
	return '76'

def read_MSNT_SystemTrace_100073_payload(buf):
	ret = {}
	ret['IrpPtr'] = read_win_type(buf, 'win:Pointer')
	ret['ExtraInfo'] = read_win_type(buf, 'win:Pointer')
	ret['NtStatus'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100074_op_code():
	return '10'

def read_MSNT_SystemTrace_100074_payload(buf):
	ret = {}
	ret['PID'] = read_win_type(buf, 'win:UInt32')
	ret['size'] = read_win_type(buf, 'win:UInt32')
	ret['daddr'] = read_win_type(buf, 'trace:IPAddr')
	ret['saddr'] = read_win_type(buf, 'trace:IPAddr')
	ret['dport'] = read_win_type(buf, 'trace:Port')
	ret['sport'] = read_win_type(buf, 'trace:Port')
	ret['startime'] = read_win_type(buf, 'win:UInt32')
	ret['endtime'] = read_win_type(buf, 'win:UInt32')
	ret['connid'] = read_win_type(buf, 'win:UInt32')
	ret['seqnum'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100075_op_code():
	return '11'

def read_MSNT_SystemTrace_100075_payload(buf):
	ret = {}
	ret['PID'] = read_win_type(buf, 'win:UInt32')
	ret['size'] = read_win_type(buf, 'win:UInt32')
	ret['daddr'] = read_win_type(buf, 'trace:IPAddr')
	ret['saddr'] = read_win_type(buf, 'trace:IPAddr')
	ret['dport'] = read_win_type(buf, 'trace:Port')
	ret['sport'] = read_win_type(buf, 'trace:Port')
	ret['connid'] = read_win_type(buf, 'win:UInt32')
	ret['seqnum'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100076_op_code():
	return '12'

def read_MSNT_SystemTrace_100076_payload(buf):
	ret = {}
	ret['PID'] = read_win_type(buf, 'win:UInt32')
	ret['size'] = read_win_type(buf, 'win:UInt32')
	ret['daddr'] = read_win_type(buf, 'trace:IPAddr')
	ret['saddr'] = read_win_type(buf, 'trace:IPAddr')
	ret['dport'] = read_win_type(buf, 'trace:Port')
	ret['sport'] = read_win_type(buf, 'trace:Port')
	ret['mss'] = read_win_type(buf, 'win:UInt16')
	ret['sackopt'] = read_win_type(buf, 'win:UInt16')
	ret['tsopt'] = read_win_type(buf, 'win:UInt16')
	ret['wsopt'] = read_win_type(buf, 'win:UInt16')
	ret['rcvwin'] = read_win_type(buf, 'win:UInt32')
	ret['rcvwinscale'] = read_win_type(buf, 'win:Int16')
	ret['sndwinscale'] = read_win_type(buf, 'win:Int16')
	ret['connid'] = read_win_type(buf, 'win:UInt32')
	ret['seqnum'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100077_op_code():
	return '13'

def read_MSNT_SystemTrace_100077_payload(buf):
	ret = {}
	ret['PID'] = read_win_type(buf, 'win:UInt32')
	ret['size'] = read_win_type(buf, 'win:UInt32')
	ret['daddr'] = read_win_type(buf, 'trace:IPAddr')
	ret['saddr'] = read_win_type(buf, 'trace:IPAddr')
	ret['dport'] = read_win_type(buf, 'trace:Port')
	ret['sport'] = read_win_type(buf, 'trace:Port')
	ret['connid'] = read_win_type(buf, 'win:UInt32')
	ret['seqnum'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100078_op_code():
	return '14'

def read_MSNT_SystemTrace_100078_payload(buf):
	ret = {}
	ret['PID'] = read_win_type(buf, 'win:UInt32')
	ret['size'] = read_win_type(buf, 'win:UInt32')
	ret['daddr'] = read_win_type(buf, 'trace:IPAddr')
	ret['saddr'] = read_win_type(buf, 'trace:IPAddr')
	ret['dport'] = read_win_type(buf, 'trace:Port')
	ret['sport'] = read_win_type(buf, 'trace:Port')
	ret['connid'] = read_win_type(buf, 'win:UInt32')
	ret['seqnum'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100079_op_code():
	return '15'

def read_MSNT_SystemTrace_100079_payload(buf):
	ret = {}
	ret['PID'] = read_win_type(buf, 'win:UInt32')
	ret['size'] = read_win_type(buf, 'win:UInt32')
	ret['daddr'] = read_win_type(buf, 'trace:IPAddr')
	ret['saddr'] = read_win_type(buf, 'trace:IPAddr')
	ret['dport'] = read_win_type(buf, 'trace:Port')
	ret['sport'] = read_win_type(buf, 'trace:Port')
	ret['mss'] = read_win_type(buf, 'win:UInt16')
	ret['sackopt'] = read_win_type(buf, 'win:UInt16')
	ret['tsopt'] = read_win_type(buf, 'win:UInt16')
	ret['wsopt'] = read_win_type(buf, 'win:UInt16')
	ret['rcvwin'] = read_win_type(buf, 'win:UInt32')
	ret['rcvwinscale'] = read_win_type(buf, 'win:Int16')
	ret['sndwinscale'] = read_win_type(buf, 'win:Int16')
	ret['connid'] = read_win_type(buf, 'win:UInt32')
	ret['seqnum'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100080_op_code():
	return '16'

def read_MSNT_SystemTrace_100080_payload(buf):
	ret = {}
	ret['PID'] = read_win_type(buf, 'win:UInt32')
	ret['size'] = read_win_type(buf, 'win:UInt32')
	ret['daddr'] = read_win_type(buf, 'trace:IPAddr')
	ret['saddr'] = read_win_type(buf, 'trace:IPAddr')
	ret['dport'] = read_win_type(buf, 'trace:Port')
	ret['sport'] = read_win_type(buf, 'trace:Port')
	ret['connid'] = read_win_type(buf, 'win:UInt32')
	ret['seqnum'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100081_op_code():
	return '17'

def read_MSNT_SystemTrace_100081_payload(buf):
	ret = {}
	ret['Proto'] = read_win_type(buf, 'win:UInt16')
	ret['FailureCode'] = read_win_type(buf, 'win:UInt16')
	return ret

def get_MSNT_SystemTrace_100082_op_code():
	return '18'

def read_MSNT_SystemTrace_100082_payload(buf):
	ret = {}
	ret['PID'] = read_win_type(buf, 'win:UInt32')
	ret['size'] = read_win_type(buf, 'win:UInt32')
	ret['daddr'] = read_win_type(buf, 'trace:IPAddr')
	ret['saddr'] = read_win_type(buf, 'trace:IPAddr')
	ret['dport'] = read_win_type(buf, 'trace:Port')
	ret['sport'] = read_win_type(buf, 'trace:Port')
	ret['connid'] = read_win_type(buf, 'win:UInt32')
	ret['seqnum'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100083_op_code():
	return '19'

def read_MSNT_SystemTrace_100083_payload(buf):
	ret = {}
	ret['PID'] = read_win_type(buf, 'win:UInt32')
	ret['size'] = read_win_type(buf, 'win:UInt32')
	ret['daddr'] = read_win_type(buf, 'trace:IPAddr')
	ret['saddr'] = read_win_type(buf, 'trace:IPAddr')
	ret['dport'] = read_win_type(buf, 'trace:Port')
	ret['sport'] = read_win_type(buf, 'trace:Port')
	ret['connid'] = read_win_type(buf, 'win:UInt32')
	ret['seqnum'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100084_op_code():
	return '20'

def read_MSNT_SystemTrace_100084_payload(buf):
	ret = {}
	ret['PID'] = read_win_type(buf, 'win:UInt32')
	ret['size'] = read_win_type(buf, 'win:UInt32')
	ret['daddr'] = read_win_type(buf, 'trace:IPAddr')
	ret['saddr'] = read_win_type(buf, 'trace:IPAddr')
	ret['dport'] = read_win_type(buf, 'trace:Port')
	ret['sport'] = read_win_type(buf, 'trace:Port')
	ret['connid'] = read_win_type(buf, 'win:UInt32')
	ret['seqnum'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100085_op_code():
	return '21'

def read_MSNT_SystemTrace_100085_payload(buf):
	ret = {}
	ret['PID'] = read_win_type(buf, 'win:UInt32')
	ret['size'] = read_win_type(buf, 'win:UInt32')
	ret['daddr'] = read_win_type(buf, 'trace:IPAddr')
	ret['saddr'] = read_win_type(buf, 'trace:IPAddr')
	ret['dport'] = read_win_type(buf, 'trace:Port')
	ret['sport'] = read_win_type(buf, 'trace:Port')
	ret['connid'] = read_win_type(buf, 'win:UInt32')
	ret['seqnum'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100086_op_code():
	return '22'

def read_MSNT_SystemTrace_100086_payload(buf):
	ret = {}
	ret['PID'] = read_win_type(buf, 'win:UInt32')
	ret['size'] = read_win_type(buf, 'win:UInt32')
	ret['daddr'] = read_win_type(buf, 'trace:IPAddr')
	ret['saddr'] = read_win_type(buf, 'trace:IPAddr')
	ret['dport'] = read_win_type(buf, 'trace:Port')
	ret['sport'] = read_win_type(buf, 'trace:Port')
	ret['connid'] = read_win_type(buf, 'win:UInt32')
	ret['seqnum'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100087_op_code():
	return '10'

def read_MSNT_SystemTrace_100087_payload(buf):
	ret = {}
	ret['PID'] = read_win_type(buf, 'win:UInt32')
	ret['size'] = read_win_type(buf, 'win:UInt32')
	ret['daddr'] = read_win_type(buf, 'trace:IPAddrV4')
	ret['saddr'] = read_win_type(buf, 'trace:IPAddrV4')
	ret['dport'] = read_win_type(buf, 'trace:Port')
	ret['sport'] = read_win_type(buf, 'trace:Port')
	ret['startime'] = read_win_type(buf, 'win:UInt32')
	ret['endtime'] = read_win_type(buf, 'win:UInt32')
	ret['seqnum'] = read_win_type(buf, 'win:UInt32')
	ret['connid'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100088_op_code():
	return '11'

def read_MSNT_SystemTrace_100088_payload(buf):
	ret = {}
	ret['PID'] = read_win_type(buf, 'win:UInt32')
	ret['size'] = read_win_type(buf, 'win:UInt32')
	ret['daddr'] = read_win_type(buf, 'trace:IPAddrV4')
	ret['saddr'] = read_win_type(buf, 'trace:IPAddrV4')
	ret['dport'] = read_win_type(buf, 'trace:Port')
	ret['sport'] = read_win_type(buf, 'trace:Port')
	ret['seqnum'] = read_win_type(buf, 'win:UInt32')
	ret['connid'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100089_op_code():
	return '13'

def read_MSNT_SystemTrace_100089_payload(buf):
	ret = {}
	ret['PID'] = read_win_type(buf, 'win:UInt32')
	ret['size'] = read_win_type(buf, 'win:UInt32')
	ret['daddr'] = read_win_type(buf, 'trace:IPAddrV4')
	ret['saddr'] = read_win_type(buf, 'trace:IPAddrV4')
	ret['dport'] = read_win_type(buf, 'trace:Port')
	ret['sport'] = read_win_type(buf, 'trace:Port')
	ret['seqnum'] = read_win_type(buf, 'win:UInt32')
	ret['connid'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100090_op_code():
	return '14'

def read_MSNT_SystemTrace_100090_payload(buf):
	ret = {}
	ret['PID'] = read_win_type(buf, 'win:UInt32')
	ret['size'] = read_win_type(buf, 'win:UInt32')
	ret['daddr'] = read_win_type(buf, 'trace:IPAddrV4')
	ret['saddr'] = read_win_type(buf, 'trace:IPAddrV4')
	ret['dport'] = read_win_type(buf, 'trace:Port')
	ret['sport'] = read_win_type(buf, 'trace:Port')
	ret['seqnum'] = read_win_type(buf, 'win:UInt32')
	ret['connid'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100091_op_code():
	return '16'

def read_MSNT_SystemTrace_100091_payload(buf):
	ret = {}
	ret['PID'] = read_win_type(buf, 'win:UInt32')
	ret['size'] = read_win_type(buf, 'win:UInt32')
	ret['daddr'] = read_win_type(buf, 'trace:IPAddrV4')
	ret['saddr'] = read_win_type(buf, 'trace:IPAddrV4')
	ret['dport'] = read_win_type(buf, 'trace:Port')
	ret['sport'] = read_win_type(buf, 'trace:Port')
	ret['seqnum'] = read_win_type(buf, 'win:UInt32')
	ret['connid'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100092_op_code():
	return '18'

def read_MSNT_SystemTrace_100092_payload(buf):
	ret = {}
	ret['PID'] = read_win_type(buf, 'win:UInt32')
	ret['size'] = read_win_type(buf, 'win:UInt32')
	ret['daddr'] = read_win_type(buf, 'trace:IPAddrV4')
	ret['saddr'] = read_win_type(buf, 'trace:IPAddrV4')
	ret['dport'] = read_win_type(buf, 'trace:Port')
	ret['sport'] = read_win_type(buf, 'trace:Port')
	ret['seqnum'] = read_win_type(buf, 'win:UInt32')
	ret['connid'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100093_op_code():
	return '12'

def read_MSNT_SystemTrace_100093_payload(buf):
	ret = {}
	ret['PID'] = read_win_type(buf, 'win:UInt32')
	ret['size'] = read_win_type(buf, 'win:UInt32')
	ret['daddr'] = read_win_type(buf, 'trace:IPAddrV4')
	ret['saddr'] = read_win_type(buf, 'trace:IPAddrV4')
	ret['dport'] = read_win_type(buf, 'trace:Port')
	ret['sport'] = read_win_type(buf, 'trace:Port')
	ret['mss'] = read_win_type(buf, 'win:UInt16')
	ret['sackopt'] = read_win_type(buf, 'win:UInt16')
	ret['tsopt'] = read_win_type(buf, 'win:UInt16')
	ret['wsopt'] = read_win_type(buf, 'win:UInt16')
	ret['rcvwin'] = read_win_type(buf, 'win:UInt32')
	ret['rcvwinscale'] = read_win_type(buf, 'win:Int16')
	ret['sndwinscale'] = read_win_type(buf, 'win:Int16')
	ret['seqnum'] = read_win_type(buf, 'win:UInt32')
	ret['connid'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100094_op_code():
	return '15'

def read_MSNT_SystemTrace_100094_payload(buf):
	ret = {}
	ret['PID'] = read_win_type(buf, 'win:UInt32')
	ret['size'] = read_win_type(buf, 'win:UInt32')
	ret['daddr'] = read_win_type(buf, 'trace:IPAddrV4')
	ret['saddr'] = read_win_type(buf, 'trace:IPAddrV4')
	ret['dport'] = read_win_type(buf, 'trace:Port')
	ret['sport'] = read_win_type(buf, 'trace:Port')
	ret['mss'] = read_win_type(buf, 'win:UInt16')
	ret['sackopt'] = read_win_type(buf, 'win:UInt16')
	ret['tsopt'] = read_win_type(buf, 'win:UInt16')
	ret['wsopt'] = read_win_type(buf, 'win:UInt16')
	ret['rcvwin'] = read_win_type(buf, 'win:UInt32')
	ret['rcvwinscale'] = read_win_type(buf, 'win:Int16')
	ret['sndwinscale'] = read_win_type(buf, 'win:Int16')
	ret['seqnum'] = read_win_type(buf, 'win:UInt32')
	ret['connid'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100095_op_code():
	return '26'

def read_MSNT_SystemTrace_100095_payload(buf):
	ret = {}
	ret['PID'] = read_win_type(buf, 'win:UInt32')
	ret['size'] = read_win_type(buf, 'win:UInt32')
	ret['daddr'] = read_win_type(buf, 'trace:IPAddrV6')
	ret['saddr'] = read_win_type(buf, 'trace:IPAddrV6')
	ret['dport'] = read_win_type(buf, 'trace:Port')
	ret['sport'] = read_win_type(buf, 'trace:Port')
	ret['startime'] = read_win_type(buf, 'win:UInt32')
	ret['endtime'] = read_win_type(buf, 'win:UInt32')
	ret['seqnum'] = read_win_type(buf, 'win:UInt32')
	ret['connid'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100096_op_code():
	return '27'

def read_MSNT_SystemTrace_100096_payload(buf):
	ret = {}
	ret['PID'] = read_win_type(buf, 'win:UInt32')
	ret['size'] = read_win_type(buf, 'win:UInt32')
	ret['daddr'] = read_win_type(buf, 'trace:IPAddrV6')
	ret['saddr'] = read_win_type(buf, 'trace:IPAddrV6')
	ret['dport'] = read_win_type(buf, 'trace:Port')
	ret['sport'] = read_win_type(buf, 'trace:Port')
	ret['seqnum'] = read_win_type(buf, 'win:UInt32')
	ret['connid'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100097_op_code():
	return '29'

def read_MSNT_SystemTrace_100097_payload(buf):
	ret = {}
	ret['PID'] = read_win_type(buf, 'win:UInt32')
	ret['size'] = read_win_type(buf, 'win:UInt32')
	ret['daddr'] = read_win_type(buf, 'trace:IPAddrV6')
	ret['saddr'] = read_win_type(buf, 'trace:IPAddrV6')
	ret['dport'] = read_win_type(buf, 'trace:Port')
	ret['sport'] = read_win_type(buf, 'trace:Port')
	ret['seqnum'] = read_win_type(buf, 'win:UInt32')
	ret['connid'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100098_op_code():
	return '30'

def read_MSNT_SystemTrace_100098_payload(buf):
	ret = {}
	ret['PID'] = read_win_type(buf, 'win:UInt32')
	ret['size'] = read_win_type(buf, 'win:UInt32')
	ret['daddr'] = read_win_type(buf, 'trace:IPAddrV6')
	ret['saddr'] = read_win_type(buf, 'trace:IPAddrV6')
	ret['dport'] = read_win_type(buf, 'trace:Port')
	ret['sport'] = read_win_type(buf, 'trace:Port')
	ret['seqnum'] = read_win_type(buf, 'win:UInt32')
	ret['connid'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100099_op_code():
	return '32'

def read_MSNT_SystemTrace_100099_payload(buf):
	ret = {}
	ret['PID'] = read_win_type(buf, 'win:UInt32')
	ret['size'] = read_win_type(buf, 'win:UInt32')
	ret['daddr'] = read_win_type(buf, 'trace:IPAddrV6')
	ret['saddr'] = read_win_type(buf, 'trace:IPAddrV6')
	ret['dport'] = read_win_type(buf, 'trace:Port')
	ret['sport'] = read_win_type(buf, 'trace:Port')
	ret['seqnum'] = read_win_type(buf, 'win:UInt32')
	ret['connid'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100100_op_code():
	return '34'

def read_MSNT_SystemTrace_100100_payload(buf):
	ret = {}
	ret['PID'] = read_win_type(buf, 'win:UInt32')
	ret['size'] = read_win_type(buf, 'win:UInt32')
	ret['daddr'] = read_win_type(buf, 'trace:IPAddrV6')
	ret['saddr'] = read_win_type(buf, 'trace:IPAddrV6')
	ret['dport'] = read_win_type(buf, 'trace:Port')
	ret['sport'] = read_win_type(buf, 'trace:Port')
	ret['seqnum'] = read_win_type(buf, 'win:UInt32')
	ret['connid'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100101_op_code():
	return '28'

def read_MSNT_SystemTrace_100101_payload(buf):
	ret = {}
	ret['PID'] = read_win_type(buf, 'win:UInt32')
	ret['size'] = read_win_type(buf, 'win:UInt32')
	ret['daddr'] = read_win_type(buf, 'trace:IPAddrV6')
	ret['saddr'] = read_win_type(buf, 'trace:IPAddrV6')
	ret['dport'] = read_win_type(buf, 'trace:Port')
	ret['sport'] = read_win_type(buf, 'trace:Port')
	ret['mss'] = read_win_type(buf, 'win:UInt16')
	ret['sackopt'] = read_win_type(buf, 'win:UInt16')
	ret['tsopt'] = read_win_type(buf, 'win:UInt16')
	ret['wsopt'] = read_win_type(buf, 'win:UInt16')
	ret['rcvwin'] = read_win_type(buf, 'win:UInt32')
	ret['rcvwinscale'] = read_win_type(buf, 'win:Int16')
	ret['sndwinscale'] = read_win_type(buf, 'win:Int16')
	ret['seqnum'] = read_win_type(buf, 'win:UInt32')
	ret['connid'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100102_op_code():
	return '31'

def read_MSNT_SystemTrace_100102_payload(buf):
	ret = {}
	ret['PID'] = read_win_type(buf, 'win:UInt32')
	ret['size'] = read_win_type(buf, 'win:UInt32')
	ret['daddr'] = read_win_type(buf, 'trace:IPAddrV6')
	ret['saddr'] = read_win_type(buf, 'trace:IPAddrV6')
	ret['dport'] = read_win_type(buf, 'trace:Port')
	ret['sport'] = read_win_type(buf, 'trace:Port')
	ret['mss'] = read_win_type(buf, 'win:UInt16')
	ret['sackopt'] = read_win_type(buf, 'win:UInt16')
	ret['tsopt'] = read_win_type(buf, 'win:UInt16')
	ret['wsopt'] = read_win_type(buf, 'win:UInt16')
	ret['rcvwin'] = read_win_type(buf, 'win:UInt32')
	ret['rcvwinscale'] = read_win_type(buf, 'win:Int16')
	ret['sndwinscale'] = read_win_type(buf, 'win:Int16')
	ret['seqnum'] = read_win_type(buf, 'win:UInt32')
	ret['connid'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100103_op_code():
	return '10'

def read_MSNT_SystemTrace_100103_payload(buf):
	ret = {}
	ret['PID'] = read_win_type(buf, 'win:UInt32')
	ret['size'] = read_win_type(buf, 'win:UInt32')
	ret['daddr'] = read_win_type(buf, 'trace:IPAddr')
	ret['saddr'] = read_win_type(buf, 'trace:IPAddr')
	ret['dport'] = read_win_type(buf, 'trace:Port')
	ret['sport'] = read_win_type(buf, 'trace:Port')
	return ret

def get_MSNT_SystemTrace_100104_op_code():
	return '11'

def read_MSNT_SystemTrace_100104_payload(buf):
	ret = {}
	ret['PID'] = read_win_type(buf, 'win:UInt32')
	ret['size'] = read_win_type(buf, 'win:UInt32')
	ret['daddr'] = read_win_type(buf, 'trace:IPAddr')
	ret['saddr'] = read_win_type(buf, 'trace:IPAddr')
	ret['dport'] = read_win_type(buf, 'trace:Port')
	ret['sport'] = read_win_type(buf, 'trace:Port')
	return ret

def get_MSNT_SystemTrace_100105_op_code():
	return '10'

def read_MSNT_SystemTrace_100105_payload(buf):
	ret = {}
	ret['PID'] = read_win_type(buf, 'win:UInt32')
	ret['size'] = read_win_type(buf, 'win:UInt32')
	ret['daddr'] = read_win_type(buf, 'trace:IPAddrV4')
	ret['saddr'] = read_win_type(buf, 'trace:IPAddrV4')
	ret['dport'] = read_win_type(buf, 'trace:Port')
	ret['sport'] = read_win_type(buf, 'trace:Port')
	ret['seqnum'] = read_win_type(buf, 'win:UInt32')
	ret['connid'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100106_op_code():
	return '11'

def read_MSNT_SystemTrace_100106_payload(buf):
	ret = {}
	ret['PID'] = read_win_type(buf, 'win:UInt32')
	ret['size'] = read_win_type(buf, 'win:UInt32')
	ret['daddr'] = read_win_type(buf, 'trace:IPAddrV4')
	ret['saddr'] = read_win_type(buf, 'trace:IPAddrV4')
	ret['dport'] = read_win_type(buf, 'trace:Port')
	ret['sport'] = read_win_type(buf, 'trace:Port')
	ret['seqnum'] = read_win_type(buf, 'win:UInt32')
	ret['connid'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100107_op_code():
	return '17'

def read_MSNT_SystemTrace_100107_payload(buf):
	ret = {}
	ret['Proto'] = read_win_type(buf, 'win:UInt16')
	ret['FailureCode'] = read_win_type(buf, 'win:UInt16')
	return ret

def get_MSNT_SystemTrace_100108_op_code():
	return '26'

def read_MSNT_SystemTrace_100108_payload(buf):
	ret = {}
	ret['PID'] = read_win_type(buf, 'win:UInt32')
	ret['size'] = read_win_type(buf, 'win:UInt32')
	ret['daddr'] = read_win_type(buf, 'trace:IPAddrV6')
	ret['saddr'] = read_win_type(buf, 'trace:IPAddrV6')
	ret['dport'] = read_win_type(buf, 'trace:Port')
	ret['sport'] = read_win_type(buf, 'trace:Port')
	ret['seqnum'] = read_win_type(buf, 'win:UInt32')
	ret['connid'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100109_op_code():
	return '27'

def read_MSNT_SystemTrace_100109_payload(buf):
	ret = {}
	ret['PID'] = read_win_type(buf, 'win:UInt32')
	ret['size'] = read_win_type(buf, 'win:UInt32')
	ret['daddr'] = read_win_type(buf, 'trace:IPAddrV6')
	ret['saddr'] = read_win_type(buf, 'trace:IPAddrV6')
	ret['dport'] = read_win_type(buf, 'trace:Port')
	ret['sport'] = read_win_type(buf, 'trace:Port')
	ret['seqnum'] = read_win_type(buf, 'win:UInt32')
	ret['connid'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100110_op_code():
	return '10'

def read_MSNT_SystemTrace_100110_payload(buf):
	ret = {}
	ret['ImageBase'] = read_win_type(buf, 'win:Pointer')
	ret['ImageSize'] = read_win_type(buf, 'win:Pointer')
	ret['ProcessId'] = read_win_type(buf, 'win:UInt32')
	ret['ImageChecksum'] = read_win_type(buf, 'win:UInt32')
	ret['TimeDateStamp'] = read_win_type(buf, 'win:UInt32')
	ret['Reserved0'] = read_win_type(buf, 'win:UInt32')
	ret['DefaultBase'] = read_win_type(buf, 'win:Pointer')
	ret['Reserved1'] = read_win_type(buf, 'win:UInt32')
	ret['Reserved2'] = read_win_type(buf, 'win:UInt32')
	ret['Reserved3'] = read_win_type(buf, 'win:UInt32')
	ret['Reserved4'] = read_win_type(buf, 'win:UInt32')
	ret['FileName'] = read_win_type(buf, 'win:UnicodeString')
	return ret

def get_MSNT_SystemTrace_100111_op_code():
	return '2'

def read_MSNT_SystemTrace_100111_payload(buf):
	ret = {}
	ret['ImageBase'] = read_win_type(buf, 'win:Pointer')
	ret['ImageSize'] = read_win_type(buf, 'win:Pointer')
	ret['ProcessId'] = read_win_type(buf, 'win:UInt32')
	ret['ImageChecksum'] = read_win_type(buf, 'win:UInt32')
	ret['TimeDateStamp'] = read_win_type(buf, 'win:UInt32')
	ret['Reserved0'] = read_win_type(buf, 'win:UInt32')
	ret['DefaultBase'] = read_win_type(buf, 'win:Pointer')
	ret['Reserved1'] = read_win_type(buf, 'win:UInt32')
	ret['Reserved2'] = read_win_type(buf, 'win:UInt32')
	ret['Reserved3'] = read_win_type(buf, 'win:UInt32')
	ret['Reserved4'] = read_win_type(buf, 'win:UInt32')
	ret['FileName'] = read_win_type(buf, 'win:UnicodeString')
	return ret

def get_MSNT_SystemTrace_100112_op_code():
	return '3'

def read_MSNT_SystemTrace_100112_payload(buf):
	ret = {}
	ret['ImageBase'] = read_win_type(buf, 'win:Pointer')
	ret['ImageSize'] = read_win_type(buf, 'win:Pointer')
	ret['ProcessId'] = read_win_type(buf, 'win:UInt32')
	ret['ImageChecksum'] = read_win_type(buf, 'win:UInt32')
	ret['TimeDateStamp'] = read_win_type(buf, 'win:UInt32')
	ret['Reserved0'] = read_win_type(buf, 'win:UInt32')
	ret['DefaultBase'] = read_win_type(buf, 'win:Pointer')
	ret['Reserved1'] = read_win_type(buf, 'win:UInt32')
	ret['Reserved2'] = read_win_type(buf, 'win:UInt32')
	ret['Reserved3'] = read_win_type(buf, 'win:UInt32')
	ret['Reserved4'] = read_win_type(buf, 'win:UInt32')
	ret['FileName'] = read_win_type(buf, 'win:UnicodeString')
	return ret

def get_MSNT_SystemTrace_100113_op_code():
	return '4'

def read_MSNT_SystemTrace_100113_payload(buf):
	ret = {}
	ret['ImageBase'] = read_win_type(buf, 'win:Pointer')
	ret['ImageSize'] = read_win_type(buf, 'win:Pointer')
	ret['ProcessId'] = read_win_type(buf, 'win:UInt32')
	ret['ImageChecksum'] = read_win_type(buf, 'win:UInt32')
	ret['TimeDateStamp'] = read_win_type(buf, 'win:UInt32')
	ret['Reserved0'] = read_win_type(buf, 'win:UInt32')
	ret['DefaultBase'] = read_win_type(buf, 'win:Pointer')
	ret['Reserved1'] = read_win_type(buf, 'win:UInt32')
	ret['Reserved2'] = read_win_type(buf, 'win:UInt32')
	ret['Reserved3'] = read_win_type(buf, 'win:UInt32')
	ret['Reserved4'] = read_win_type(buf, 'win:UInt32')
	ret['FileName'] = read_win_type(buf, 'win:UnicodeString')
	return ret

def get_MSNT_SystemTrace_100114_op_code():
	return '10'

def read_MSNT_SystemTrace_100114_payload(buf):
	ret = {}
	ret['VirtualAddress'] = read_win_type(buf, 'win:Pointer')
	ret['ProgramCounter'] = read_win_type(buf, 'win:Pointer')
	return ret

def get_MSNT_SystemTrace_100115_op_code():
	return '11'

def read_MSNT_SystemTrace_100115_payload(buf):
	ret = {}
	ret['VirtualAddress'] = read_win_type(buf, 'win:Pointer')
	ret['ProgramCounter'] = read_win_type(buf, 'win:Pointer')
	return ret

def get_MSNT_SystemTrace_100116_op_code():
	return '12'

def read_MSNT_SystemTrace_100116_payload(buf):
	ret = {}
	ret['VirtualAddress'] = read_win_type(buf, 'win:Pointer')
	ret['ProgramCounter'] = read_win_type(buf, 'win:Pointer')
	return ret

def get_MSNT_SystemTrace_100117_op_code():
	return '13'

def read_MSNT_SystemTrace_100117_payload(buf):
	ret = {}
	ret['VirtualAddress'] = read_win_type(buf, 'win:Pointer')
	ret['ProgramCounter'] = read_win_type(buf, 'win:Pointer')
	return ret

def get_MSNT_SystemTrace_100118_op_code():
	return '14'

def read_MSNT_SystemTrace_100118_payload(buf):
	ret = {}
	ret['VirtualAddress'] = read_win_type(buf, 'win:Pointer')
	ret['ProgramCounter'] = read_win_type(buf, 'win:Pointer')
	return ret

def get_MSNT_SystemTrace_100119_op_code():
	return '15'

def read_MSNT_SystemTrace_100119_payload(buf):
	ret = {}
	ret['VirtualAddress'] = read_win_type(buf, 'win:Pointer')
	ret['ProgramCounter'] = read_win_type(buf, 'win:Pointer')
	return ret

def get_MSNT_SystemTrace_100120_op_code():
	return '32'

def read_MSNT_SystemTrace_100120_payload(buf):
	ret = {}
	ret['InitialTime'] = read_win_type(buf, 'trace:WmiTime')
	ret['ReadOffset'] = read_win_type(buf, 'win:UInt64')
	ret['VirtualAddress'] = read_win_type(buf, 'win:Pointer')
	ret['FileObject'] = read_win_type(buf, 'win:Pointer')
	ret['TThreadId'] = read_win_type(buf, 'win:UInt32')
	ret['ByteCount'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100121_op_code():
	return '100'

def read_MSNT_SystemTrace_100121_payload(buf):
	ret = {}
	ret['HeapHandle'] = read_win_type(buf, 'win:Pointer')
	ret['HRFlags'] = read_win_type(buf, 'win:UInt32')
	ret['HRPid'] = read_win_type(buf, 'win:UInt32')
	ret['HRRangeCount'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100122_op_code():
	return '101'

def read_MSNT_SystemTrace_100122_payload(buf):
	ret = {}
	ret['HeapHandle'] = read_win_type(buf, 'win:Pointer')
	ret['FirstRangeSize'] = read_win_type(buf, 'trace:SizeT')
	ret['HRCreateFlags'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100123_op_code():
	return '102'

def read_MSNT_SystemTrace_100123_payload(buf):
	ret = {}
	ret['HeapHandle'] = read_win_type(buf, 'win:Pointer')
	ret['HRAddress'] = read_win_type(buf, 'win:Pointer')
	ret['HRSize'] = read_win_type(buf, 'trace:SizeT')
	return ret

def get_MSNT_SystemTrace_100124_op_code():
	return '103'

def read_MSNT_SystemTrace_100124_payload(buf):
	ret = {}
	ret['HeapHandle'] = read_win_type(buf, 'win:Pointer')
	ret['HRAddress'] = read_win_type(buf, 'win:Pointer')
	ret['HRSize'] = read_win_type(buf, 'trace:SizeT')
	return ret

def get_MSNT_SystemTrace_100125_op_code():
	return '104'

def read_MSNT_SystemTrace_100125_payload(buf):
	ret = {}
	ret['HeapHandle'] = read_win_type(buf, 'win:Pointer')
	return ret

def get_MSNT_SystemTrace_100126_op_code():
	return '105'

def read_MSNT_SystemTrace_100126_payload(buf):
	ret = {}
	ret['FileObject'] = read_win_type(buf, 'win:Pointer')
	ret['DeviceChar'] = read_win_type(buf, 'win:UInt32')
	ret['FileChar'] = read_win_type(buf, 'win:UInt16')
	ret['LoadFlags'] = read_win_type(buf, 'win:UInt16')
	return ret

def get_MSNT_SystemTrace_100127_op_code():
	return '46'

def read_MSNT_SystemTrace_100127_payload(buf):
	ret = {}
	ret['InstructionPointer'] = read_win_type(buf, 'win:Pointer')
	ret['ThreadId'] = read_win_type(buf, 'win:UInt32')
	ret['Count'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100128_op_code():
	return '72'

def read_MSNT_SystemTrace_100128_payload(buf):
	ret = {}
	ret['Source'] = read_win_type(buf, 'win:UInt32')
	ret['NewInterval'] = read_win_type(buf, 'win:UInt32')
	ret['OldInterval'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100129_op_code():
	return '73'

def read_MSNT_SystemTrace_100129_payload(buf):
	ret = {}
	ret['Source'] = read_win_type(buf, 'win:UInt32')
	ret['NewInterval'] = read_win_type(buf, 'win:UInt32')
	ret['OldInterval'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100130_op_code():
	return '74'

def read_MSNT_SystemTrace_100130_payload(buf):
	ret = {}
	ret['Source'] = read_win_type(buf, 'win:UInt32')
	ret['NewInterval'] = read_win_type(buf, 'win:UInt32')
	ret['OldInterval'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100131_op_code():
	return '51'

def read_MSNT_SystemTrace_100131_payload(buf):
	ret = {}
	ret['SysCallAddress'] = read_win_type(buf, 'win:Pointer')
	return ret

def get_MSNT_SystemTrace_100132_op_code():
	return '52'

def read_MSNT_SystemTrace_100132_payload(buf):
	ret = {}
	ret['SysCallNtStatus'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100133_op_code():
	return '67'

def read_MSNT_SystemTrace_100133_payload(buf):
	ret = {}
	ret['InitialTime'] = read_win_type(buf, 'trace:WmiTime')
	ret['Routine'] = read_win_type(buf, 'win:Pointer')
	ret['ReturnValue'] = read_win_type(buf, 'win:UInt8')
	ret['Vector'] = read_win_type(buf, 'win:UInt8')
	ret['Reserved'] = read_win_type(buf, 'win:UInt16')
	return ret

def get_MSNT_SystemTrace_100134_op_code():
	return '66'

def read_MSNT_SystemTrace_100134_payload(buf):
	ret = {}
	ret['InitialTime'] = read_win_type(buf, 'trace:WmiTime')
	ret['Routine'] = read_win_type(buf, 'win:Pointer')
	return ret

def get_MSNT_SystemTrace_100135_op_code():
	return '68'

def read_MSNT_SystemTrace_100135_payload(buf):
	ret = {}
	ret['InitialTime'] = read_win_type(buf, 'trace:WmiTime')
	ret['Routine'] = read_win_type(buf, 'win:Pointer')
	return ret

def get_MSNT_SystemTrace_100136_op_code():
	return '69'

def read_MSNT_SystemTrace_100136_payload(buf):
	ret = {}
	ret['InitialTime'] = read_win_type(buf, 'trace:WmiTime')
	ret['Routine'] = read_win_type(buf, 'win:Pointer')
	return ret

def get_MSNT_SystemTrace_100137_op_code():
	return '58'

def read_MSNT_SystemTrace_100137_payload(buf):
	ret = {}
	return ret

def get_MSNT_SystemTrace_100138_op_code():
	return '32'

def read_MSNT_SystemTrace_100138_payload(buf):
	ret = {}
	ret['EventTimeStamp'] = read_win_type(buf, 'win:UInt64')
	ret['StackProcess'] = read_win_type(buf, 'win:UInt32')
	ret['StackThread'] = read_win_type(buf, 'win:UInt32')
	ret['Stack1'] = read_win_type(buf, 'win:Pointer')
	ret['Stack2'] = read_win_type(buf, 'win:Pointer')
	ret['Stack3'] = read_win_type(buf, 'win:Pointer')
	ret['Stack4'] = read_win_type(buf, 'win:Pointer')
	ret['Stack5'] = read_win_type(buf, 'win:Pointer')
	ret['Stack6'] = read_win_type(buf, 'win:Pointer')
	ret['Stack7'] = read_win_type(buf, 'win:Pointer')
	ret['Stack8'] = read_win_type(buf, 'win:Pointer')
	ret['Stack9'] = read_win_type(buf, 'win:Pointer')
	ret['Stack10'] = read_win_type(buf, 'win:Pointer')
	ret['Stack11'] = read_win_type(buf, 'win:Pointer')
	ret['Stack12'] = read_win_type(buf, 'win:Pointer')
	ret['Stack13'] = read_win_type(buf, 'win:Pointer')
	ret['Stack14'] = read_win_type(buf, 'win:Pointer')
	ret['Stack15'] = read_win_type(buf, 'win:Pointer')
	ret['Stack16'] = read_win_type(buf, 'win:Pointer')
	ret['Stack17'] = read_win_type(buf, 'win:Pointer')
	ret['Stack18'] = read_win_type(buf, 'win:Pointer')
	ret['Stack19'] = read_win_type(buf, 'win:Pointer')
	ret['Stack20'] = read_win_type(buf, 'win:Pointer')
	ret['Stack21'] = read_win_type(buf, 'win:Pointer')
	ret['Stack22'] = read_win_type(buf, 'win:Pointer')
	ret['Stack23'] = read_win_type(buf, 'win:Pointer')
	ret['Stack24'] = read_win_type(buf, 'win:Pointer')
	ret['Stack25'] = read_win_type(buf, 'win:Pointer')
	ret['Stack26'] = read_win_type(buf, 'win:Pointer')
	ret['Stack27'] = read_win_type(buf, 'win:Pointer')
	ret['Stack28'] = read_win_type(buf, 'win:Pointer')
	ret['Stack29'] = read_win_type(buf, 'win:Pointer')
	ret['Stack30'] = read_win_type(buf, 'win:Pointer')
	ret['Stack31'] = read_win_type(buf, 'win:Pointer')
	ret['Stack32'] = read_win_type(buf, 'win:Pointer')
	return ret

def get_MSNT_SystemTrace_100139_op_code():
	return '33'

def read_MSNT_SystemTrace_100139_payload(buf):
	ret = {}
	ret['MessageID'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100140_op_code():
	return '34'

def read_MSNT_SystemTrace_100140_payload(buf):
	ret = {}
	ret['MessageID'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100141_op_code():
	return '35'

def read_MSNT_SystemTrace_100141_payload(buf):
	ret = {}
	ret['MessageID'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100142_op_code():
	return '36'

def read_MSNT_SystemTrace_100142_payload(buf):
	ret = {}
	ret['IsServerPort'] = read_win_type(buf, 'win:UInt32')
	ret['PortName'] = read_win_type(buf, 'win:AnsiString')
	return ret

def get_MSNT_SystemTrace_100143_op_code():
	return '37'

def read_MSNT_SystemTrace_100143_payload(buf):
	ret = {}
	ret['Status'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100144_op_code():
	return '32'

def read_MSNT_SystemTrace_100144_payload(buf):
	ret = {}
	return ret

def get_MSNT_SystemTrace_100145_op_code():
	return '10'

def read_MSNT_SystemTrace_100145_payload(buf):
	ret = {}
	ret['MHz'] = read_win_type(buf, 'win:UInt32')
	ret['NumberOfProcessors'] = read_win_type(buf, 'win:UInt32')
	ret['MemSize'] = read_win_type(buf, 'win:UInt32')
	ret['PageSize'] = read_win_type(buf, 'win:UInt32')
	ret['AllocationGranularity'] = read_win_type(buf, 'win:UInt32')
	ret['ComputerName'] = read_win_type(buf, 'trace:UnicodeChar')
	ret['DomainName'] = read_win_type(buf, 'trace:UnicodeChar')
	ret['HyperThreadingFlag'] = read_win_type(buf, 'win:Pointer')
	return ret

def get_MSNT_SystemTrace_100146_op_code():
	return '11'

def read_MSNT_SystemTrace_100146_payload(buf):
	ret = {}
	ret['DiskNumber'] = read_win_type(buf, 'win:UInt32')
	ret['BytesPerSector'] = read_win_type(buf, 'win:UInt32')
	ret['SectorsPerTrack'] = read_win_type(buf, 'win:UInt32')
	ret['TracksPerCylinder'] = read_win_type(buf, 'win:UInt32')
	ret['Cylinders'] = read_win_type(buf, 'win:UInt64')
	ret['SCSIPort'] = read_win_type(buf, 'win:UInt32')
	ret['SCSIPath'] = read_win_type(buf, 'win:UInt32')
	ret['SCSITarget'] = read_win_type(buf, 'win:UInt32')
	ret['SCSILun'] = read_win_type(buf, 'win:UInt32')
	ret['Manufacturer'] = read_win_type(buf, 'trace:UnicodeChar')
	ret['PartitionCount'] = read_win_type(buf, 'win:UInt32')
	ret['WriteCacheEnabled'] = read_win_type(buf, 'win:UInt8')
	ret['Pad'] = read_win_type(buf, 'win:UInt8')
	ret['BootDriveLetter'] = read_win_type(buf, 'trace:UnicodeChar')
	ret['Spare'] = read_win_type(buf, 'trace:UnicodeChar')
	return ret

def get_MSNT_SystemTrace_100147_op_code():
	return '12'

def read_MSNT_SystemTrace_100147_payload(buf):
	ret = {}
	ret['StartOffset'] = read_win_type(buf, 'win:UInt64')
	ret['PartitionSize'] = read_win_type(buf, 'win:UInt64')
	ret['DiskNumber'] = read_win_type(buf, 'win:UInt32')
	ret['Size'] = read_win_type(buf, 'win:UInt32')
	ret['DriveType'] = read_win_type(buf, 'win:UInt32')
	ret['DriveLetterString'] = read_win_type(buf, 'trace:UnicodeChar')
	ret['Pad1'] = read_win_type(buf, 'win:UInt32')
	ret['PartitionNumber'] = read_win_type(buf, 'win:UInt32')
	ret['SectorsPerCluster'] = read_win_type(buf, 'win:UInt32')
	ret['BytesPerSector'] = read_win_type(buf, 'win:UInt32')
	ret['Pad2'] = read_win_type(buf, 'win:UInt32')
	ret['NumberOfFreeClusters'] = read_win_type(buf, 'win:Int64')
	ret['TotalNumberOfClusters'] = read_win_type(buf, 'win:Int64')
	ret['FileSystem'] = read_win_type(buf, 'trace:UnicodeChar')
	ret['VolumeExt'] = read_win_type(buf, 'win:UInt32')
	ret['Pad3'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100148_op_code():
	return '13'

def read_MSNT_SystemTrace_100148_payload(buf):
	ret = {}
	ret['PhysicalAddr'] = read_win_type(buf, 'win:UInt64')
	ret['PhysicalAddrLen'] = read_win_type(buf, 'win:UInt32')
	ret['Ipv4Index'] = read_win_type(buf, 'win:UInt32')
	ret['Ipv6Index'] = read_win_type(buf, 'win:UInt32')
	ret['NICDescription'] = read_win_type(buf, 'win:UnicodeString')
	ret['IpAddresses'] = read_win_type(buf, 'win:UnicodeString')
	ret['DnsServerAddresses'] = read_win_type(buf, 'win:UnicodeString')
	return ret

def get_MSNT_SystemTrace_100149_op_code():
	return '14'

def read_MSNT_SystemTrace_100149_payload(buf):
	ret = {}
	ret['MemorySize'] = read_win_type(buf, 'win:UInt32')
	ret['XResolution'] = read_win_type(buf, 'win:UInt32')
	ret['YResolution'] = read_win_type(buf, 'win:UInt32')
	ret['BitsPerPixel'] = read_win_type(buf, 'win:UInt32')
	ret['VRefresh'] = read_win_type(buf, 'win:UInt32')
	ret['ChipType'] = read_win_type(buf, 'trace:UnicodeChar')
	ret['DACType'] = read_win_type(buf, 'trace:UnicodeChar')
	ret['AdapterString'] = read_win_type(buf, 'trace:UnicodeChar')
	ret['BiosString'] = read_win_type(buf, 'trace:UnicodeChar')
	ret['DeviceId'] = read_win_type(buf, 'trace:UnicodeChar')
	ret['StateFlags'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100150_op_code():
	return '15'

def read_MSNT_SystemTrace_100150_payload(buf):
	ret = {}
	ret['ProcessId'] = read_win_type(buf, 'win:UInt32')
	ret['ServiceState'] = read_win_type(buf, 'win:UInt32')
	ret['SubProcessTag'] = read_win_type(buf, 'win:UInt32')
	ret['ServiceName'] = read_win_type(buf, 'win:UnicodeString')
	ret['DisplayName'] = read_win_type(buf, 'win:UnicodeString')
	ret['ProcessName'] = read_win_type(buf, 'win:UnicodeString')
	return ret

def get_MSNT_SystemTrace_100151_op_code():
	return '16'

def read_MSNT_SystemTrace_100151_payload(buf):
	ret = {}
	ret['S1'] = read_win_type(buf, 'win:UInt8')
	ret['S2'] = read_win_type(buf, 'win:UInt8')
	ret['S3'] = read_win_type(buf, 'win:UInt8')
	ret['S4'] = read_win_type(buf, 'win:UInt8')
	ret['S5'] = read_win_type(buf, 'win:UInt8')
	ret['Pad1'] = read_win_type(buf, 'win:UInt8')
	ret['Pad2'] = read_win_type(buf, 'win:UInt8')
	ret['Pad3'] = read_win_type(buf, 'win:UInt8')
	return ret

def get_MSNT_SystemTrace_100152_op_code():
	return '21'

def read_MSNT_SystemTrace_100152_payload(buf):
	ret = {}
	ret['IRQAffinity'] = read_win_type(buf, 'win:UInt64')
	ret['IRQNum'] = read_win_type(buf, 'win:UInt32')
	ret['DeviceDescriptionLen'] = read_win_type(buf, 'win:UInt32')
	ret['DeviceDescription'] = read_win_type(buf, 'win:UnicodeString')
	return ret

def get_MSNT_SystemTrace_100153_op_code():
	return '22'

def read_MSNT_SystemTrace_100153_payload(buf):
	ret = {}
	ret['IDLength'] = read_win_type(buf, 'win:UInt32')
	ret['DescriptionLength'] = read_win_type(buf, 'win:UInt32')
	ret['FriendlyNameLength'] = read_win_type(buf, 'win:UInt32')
	ret['DeviceID'] = read_win_type(buf, 'win:UnicodeString')
	ret['DeviceDescription'] = read_win_type(buf, 'win:UnicodeString')
	ret['FriendlyName'] = read_win_type(buf, 'win:UnicodeString')
	return ret

def get_MSNT_SystemTrace_100154_op_code():
	return '17'

def read_MSNT_SystemTrace_100154_payload(buf):
	ret = {}
	ret['TcbTablePartitions'] = read_win_type(buf, 'win:UInt32')
	ret['MaxHashTableSize'] = read_win_type(buf, 'win:UInt32')
	ret['MaxUserPort'] = read_win_type(buf, 'win:UInt32')
	ret['TcpTimedWaitDelay'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_MSNT_SystemTrace_100155_op_code():
	return '23'

def read_MSNT_SystemTrace_100155_payload(buf):
	ret = {}
	ret['TargetId'] = read_win_type(buf, 'win:UInt32')
	ret['DeviceType'] = read_win_type(buf, 'win:UInt32')
	ret['DeviceTimingMode'] = read_win_type(buf, 'win:UInt32')
	ret['LocationInformationLen'] = read_win_type(buf, 'win:UInt32')
	ret['LocationInformation'] = read_win_type(buf, 'win:UnicodeString')
	return ret

def get_ThreadPool_100000_op_code():
	return '32'

def read_ThreadPool_100000_payload(buf):
	ret = {}
	ret['PoolId'] = read_win_type(buf, 'win:Pointer')
	ret['TaskId'] = read_win_type(buf, 'win:Pointer')
	ret['CallbackFunction'] = read_win_type(buf, 'win:Pointer')
	ret['CallbackContext'] = read_win_type(buf, 'win:Pointer')
	ret['SubProcessTag'] = read_win_type(buf, 'win:Pointer')
	return ret

def get_ThreadPool_100001_op_code():
	return '34'

def read_ThreadPool_100001_payload(buf):
	ret = {}
	ret['PoolId'] = read_win_type(buf, 'win:Pointer')
	ret['TaskId'] = read_win_type(buf, 'win:Pointer')
	ret['CallbackFunction'] = read_win_type(buf, 'win:Pointer')
	ret['CallbackContext'] = read_win_type(buf, 'win:Pointer')
	ret['SubProcessTag'] = read_win_type(buf, 'win:Pointer')
	return ret

def get_ThreadPool_100002_op_code():
	return '33'

def read_ThreadPool_100002_payload(buf):
	ret = {}
	ret['TaskId'] = read_win_type(buf, 'win:Pointer')
	return ret

def get_ThreadPool_100003_op_code():
	return '35'

def read_ThreadPool_100003_payload(buf):
	ret = {}
	ret['TaskId'] = read_win_type(buf, 'win:Pointer')
	return ret

def get_ThreadPool_100004_op_code():
	return '36'

def read_ThreadPool_100004_payload(buf):
	ret = {}
	ret['TaskId'] = read_win_type(buf, 'win:Pointer')
	ret['CancelCount'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_ThreadPool_100005_op_code():
	return '37'

def read_ThreadPool_100005_payload(buf):
	ret = {}
	ret['PoolId'] = read_win_type(buf, 'win:Pointer')
	return ret

def get_ThreadPool_100006_op_code():
	return '38'

def read_ThreadPool_100006_payload(buf):
	ret = {}
	ret['PoolId'] = read_win_type(buf, 'win:Pointer')
	return ret

def get_ThreadPool_100007_op_code():
	return '39'

def read_ThreadPool_100007_payload(buf):
	ret = {}
	ret['PoolId'] = read_win_type(buf, 'win:Pointer')
	ret['ThreadNum'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_ThreadPool_100008_op_code():
	return '40'

def read_ThreadPool_100008_payload(buf):
	ret = {}
	ret['PoolId'] = read_win_type(buf, 'win:Pointer')
	ret['ThreadNum'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_HeapTraceProvider_100000_op_code():
	return '32'

def read_HeapTraceProvider_100000_payload(buf):
	ret = {}
	ret['HeapHandle'] = read_win_type(buf, 'win:Pointer')
	ret['HeapFlags'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_HeapTraceProvider_100001_op_code():
	return '33'

def read_HeapTraceProvider_100001_payload(buf):
	ret = {}
	ret['HeapHandle'] = read_win_type(buf, 'win:Pointer')
	ret['AllocSize'] = read_win_type(buf, 'trace:SizeT')
	ret['AllocAddress'] = read_win_type(buf, 'win:Pointer')
	ret['SourceId'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_HeapTraceProvider_100002_op_code():
	return '34'

def read_HeapTraceProvider_100002_payload(buf):
	ret = {}
	ret['HeapHandle'] = read_win_type(buf, 'win:Pointer')
	ret['NewAllocAddress'] = read_win_type(buf, 'win:Pointer')
	ret['OldAllocAddress'] = read_win_type(buf, 'win:Pointer')
	ret['NewAllocSize'] = read_win_type(buf, 'trace:SizeT')
	ret['OldAllocSize'] = read_win_type(buf, 'trace:SizeT')
	ret['SourceId'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_HeapTraceProvider_100003_op_code():
	return '36'

def read_HeapTraceProvider_100003_payload(buf):
	ret = {}
	ret['HeapHandle'] = read_win_type(buf, 'win:Pointer')
	ret['FreeAddress'] = read_win_type(buf, 'win:Pointer')
	ret['SourceId'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_HeapTraceProvider_100004_op_code():
	return '37'

def read_HeapTraceProvider_100004_payload(buf):
	ret = {}
	ret['HeapHandle'] = read_win_type(buf, 'win:Pointer')
	ret['CommittedSize'] = read_win_type(buf, 'trace:SizeT')
	ret['CommitAddress'] = read_win_type(buf, 'win:Pointer')
	ret['FreeSpace'] = read_win_type(buf, 'trace:SizeT')
	ret['CommittedSpace'] = read_win_type(buf, 'trace:SizeT')
	ret['ReservedSpace'] = read_win_type(buf, 'trace:SizeT')
	ret['NoOfUCRs'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_HeapTraceProvider_100005_op_code():
	return '38'

def read_HeapTraceProvider_100005_payload(buf):
	ret = {}
	ret['HeapHandle'] = read_win_type(buf, 'win:Pointer')
	ret['FreeSpace'] = read_win_type(buf, 'trace:SizeT')
	ret['CommittedSpace'] = read_win_type(buf, 'trace:SizeT')
	ret['ReservedSpace'] = read_win_type(buf, 'trace:SizeT')
	ret['HeapFlags'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_HeapTraceProvider_100006_op_code():
	return '42'

def read_HeapTraceProvider_100006_payload(buf):
	ret = {}
	ret['HeapHandle'] = read_win_type(buf, 'win:Pointer')
	ret['DeCommittedSize'] = read_win_type(buf, 'trace:SizeT')
	ret['DeCommitAddress'] = read_win_type(buf, 'win:Pointer')
	ret['FreeSpace'] = read_win_type(buf, 'trace:SizeT')
	ret['CommittedSpace'] = read_win_type(buf, 'trace:SizeT')
	ret['ReservedSpace'] = read_win_type(buf, 'trace:SizeT')
	ret['NoOfUCRs'] = read_win_type(buf, 'win:UInt32')
	return ret

def get_HeapTraceProvider_100007_op_code():
	return '35'

def read_HeapTraceProvider_100007_payload(buf):
	ret = {}
	ret['HeapHandle'] = read_win_type(buf, 'win:Pointer')
	return ret

def get_HeapTraceProvider_100008_op_code():
	return '43'

def read_HeapTraceProvider_100008_payload(buf):
	ret = {}
	ret['HeapHandle'] = read_win_type(buf, 'win:Pointer')
	return ret

def get_HeapTraceProvider_100009_op_code():
	return '44'

def read_HeapTraceProvider_100009_payload(buf):
	ret = {}
	ret['HeapHandle'] = read_win_type(buf, 'win:Pointer')
	return ret

def get_HeapTraceProvider_100010_op_code():
	return '45'

def read_HeapTraceProvider_100010_payload(buf):
	ret = {}
	ret['HeapHandle'] = read_win_type(buf, 'win:Pointer')
	return ret

def get_HeapTraceProvider_100011_op_code():
	return '46'

def read_HeapTraceProvider_100011_payload(buf):
	ret = {}
	ret['HeapHandle'] = read_win_type(buf, 'win:Pointer')
	return ret

def get_CritSecTraceProvider_100000_op_code():
	return '34'

def read_CritSecTraceProvider_100000_payload(buf):
	ret = {}
	ret['LockCount'] = read_win_type(buf, 'win:UInt32')
	ret['SpinCount'] = read_win_type(buf, 'win:UInt32')
	ret['OwningThread'] = read_win_type(buf, 'win:Pointer')
	ret['CritSecAddr'] = read_win_type(buf, 'win:Pointer')
	return ret

def get_CritSecTraceProvider_100001_op_code():
	return '35'

def read_CritSecTraceProvider_100001_payload(buf):
	ret = {}
	ret['SpinCount'] = read_win_type(buf, 'win:Pointer')
	ret['CritSecAddr'] = read_win_type(buf, 'win:Pointer')
	return ret

