### THIS IS AUTOGENERATED CODE
### Generated: 20200908 16:05:58
### Generated by: evtparsergen.py-23526ee
### Generated from: https://github.com/microsoft/perfview/blob/P2.0.59/src/TraceEvent/Parsers/ASPNetTraceEventParser.man.xml

from .utils import *

def read_AspNet_10000_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	ret['Method'] = read_win_type(buf, 'win:AnsiString')
	ret['Path'] = read_win_type(buf, 'win:AnsiString')
	ret['QueryString'] = read_win_type(buf, 'win:AnsiString')

def read_AspNet_10001_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')

def read_AspNet_10002_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')

def read_AspNet_10003_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')

def read_AspNet_10004_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')

def read_AspNet_10005_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')

def read_AspNet_10006_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	ret['DomainId'] = read_win_type(buf, 'win:UnicodeString')

def read_AspNet_10007_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	ret['HandlerName'] = read_win_type(buf, 'win:UnicodeString')
	ret['EventName'] = read_win_type(buf, 'win:UnicodeString')

def read_AspNet_10008_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')

def read_AspNet_10009_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	ret['ModuleName'] = read_win_type(buf, 'win:UnicodeString')

def read_AspNet_10010_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	ret['ModuleName'] = read_win_type(buf, 'win:UnicodeString')

def read_AspNet_10011_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')

def read_AspNet_10012_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')

def read_AspNet_10013_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')

def read_AspNet_10014_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')

def read_AspNet_10015_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')

def read_AspNet_10016_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	ret['Files'] = read_win_type(buf, 'win:UnicodeString')
	ret['Status'] = read_win_type(buf, 'win:UnicodeString')

def read_AspNet_10017_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')

def read_AspNet_10018_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')

def read_AspNet_10019_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	ret['ResolverType'] = read_win_type(buf, 'win:UnicodeString')
	ret['SessionId'] = read_win_type(buf, 'win:UnicodeString')

def read_AspNet_10020_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	ret['ResolverResult'] = read_win_type(buf, 'win:UnicodeString')

def read_AspNet_10021_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')

def read_AspNet_10022_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')

def read_AspNet_10023_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')

def read_AspNet_10024_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')

def read_AspNet_10025_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')

def read_AspNet_10026_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')

def read_AspNet_10027_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')

def read_AspNet_10028_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')

def read_AspNet_10029_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')

def read_AspNet_10030_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')

def read_AspNet_10031_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')

def read_AspNet_10032_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')

def read_AspNet_10033_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')

def read_AspNet_10034_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')

def read_AspNet_10035_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')

def read_AspNet_10036_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')

def read_AspNet_10037_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')

def read_AspNet_10038_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')

def read_AspNet_10039_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')

def read_AspNet_10040_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')

def read_AspNet_10041_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')

def read_AspNet_10042_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')

def read_AspNet_10043_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')

def read_AspNet_10044_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	ret['User'] = read_win_type(buf, 'win:UnicodeString')

def read_AspNet_10045_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	ret['Provider'] = read_win_type(buf, 'win:UnicodeString')
	ret['User'] = read_win_type(buf, 'win:UnicodeString')
	ret['Role'] = read_win_type(buf, 'win:UnicodeString')
	ret['Status'] = read_win_type(buf, 'win:UnicodeString')

def read_AspNet_10046_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	ret['Provider'] = read_win_type(buf, 'win:UnicodeString')
	ret['User'] = read_win_type(buf, 'win:UnicodeString')
	ret['Roles'] = read_win_type(buf, 'win:UnicodeString')

def read_AspNet_10047_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')

def read_AspNet_10048_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	ret['Provider'] = read_win_type(buf, 'win:UnicodeString')
	ret['User'] = read_win_type(buf, 'win:UnicodeString')

def read_AspNet_10049_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	ret['EventClassName'] = read_win_type(buf, 'win:UnicodeString')
	ret['EventCode'] = read_win_type(buf, 'win:UnicodeString')
	ret['EventDetailCode'] = read_win_type(buf, 'win:UnicodeString')

def read_AspNet_10050_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')

def read_AspNet_10051_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	ret['ProviderName'] = read_win_type(buf, 'win:UnicodeString')
	ret['RuleName'] = read_win_type(buf, 'win:UnicodeString')
	ret['EventGroupName'] = read_win_type(buf, 'win:UnicodeString')

def read_AspNet_10052_payload(buf):
	ret = {}
	ret['ConnID'] = read_win_type(buf, 'win:UInt64')
	ret['ContextId'] = read_win_type(buf, 'win:GUID')

def read_AspNet_10053_payload(buf):
	ret = {}
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	ret['Uri'] = read_win_type(buf, 'win:UnicodeString')
	ret['TraceWarningMsg'] = read_win_type(buf, 'win:UnicodeString')

def read_AspNet_10054_payload(buf):
	ret = {}
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	ret['Uri'] = read_win_type(buf, 'win:UnicodeString')
	ret['TraceWriteMsg'] = read_win_type(buf, 'win:UnicodeString')

def read_AspNet_10055_payload(buf):
	ret = {}
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	ret['Uri'] = read_win_type(buf, 'win:UnicodeString')
	ret['TraceWriteMsg'] = read_win_type(buf, 'win:UnicodeString')

def read_AspNet_10056_payload(buf):
	ret = {}
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	ret['Uri'] = read_win_type(buf, 'win:UnicodeString')
	ret['TraceWriteMsg'] = read_win_type(buf, 'win:UnicodeString')

def read_AspNet_10057_payload(buf):
	ret = {}
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	ret['Uri'] = read_win_type(buf, 'win:UnicodeString')
	ret['TraceWriteMsg'] = read_win_type(buf, 'win:UnicodeString')

def read_AspNet_10058_payload(buf):
	ret = {}
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	ret['Uri'] = read_win_type(buf, 'win:UnicodeString')
	ret['TraceWriteMsg'] = read_win_type(buf, 'win:UnicodeString')

def read_AspNet_10059_payload(buf):
	ret = {}
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	ret['Uri'] = read_win_type(buf, 'win:UnicodeString')
	ret['TraceWriteMsg'] = read_win_type(buf, 'win:UnicodeString')

def read_AspNet_10060_payload(buf):
	ret = {}
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	ret['Uri'] = read_win_type(buf, 'win:UnicodeString')
	ret['TraceWriteMsg'] = read_win_type(buf, 'win:UnicodeString')

def read_AspNet_10061_payload(buf):
	ret = {}
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	ret['Uri'] = read_win_type(buf, 'win:UnicodeString')
	ret['TraceWriteMsg'] = read_win_type(buf, 'win:UnicodeString')

def read_AspNet_10062_payload(buf):
	ret = {}
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	ret['Uri'] = read_win_type(buf, 'win:UnicodeString')
	ret['TraceWriteMsg'] = read_win_type(buf, 'win:UnicodeString')

def read_AspNet_10063_payload(buf):
	ret = {}
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	ret['Uri'] = read_win_type(buf, 'win:UnicodeString')
	ret['TraceWriteMsg'] = read_win_type(buf, 'win:UnicodeString')

def read_AspNet_10064_payload(buf):
	ret = {}
	ret['ContextId'] = read_win_type(buf, 'win:GUID')
	ret['Uri'] = read_win_type(buf, 'win:UnicodeString')
	ret['TraceWriteMsg'] = read_win_type(buf, 'win:UnicodeString')

