### THIS IS AUTOGENERATED CODE
### Generated: 20200908 16:05:13
### Generated by: evtparsergen.py-23526ee
### Generated from: https://github.com/microsoft/perfview/blob/P2.0.59/src/TraceEvent/Parsers/ClrEtwAll.man

from .utils import *

def read_Microsoft_Windows_DotNETRuntime_1_payload(buf):
	ret = {}
	ret['Count'] = read_win_type(buf, 'win:UInt32')
	ret['Depth'] = read_win_type(buf, 'win:UInt32')
	ret['Reason'] = read_win_type(buf, 'win:UInt32')
	ret['Type'] = read_win_type(buf, 'win:UInt32')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')
	ret['ClientSequenceNumber'] = read_win_type(buf, 'win:UInt64')

def read_Microsoft_Windows_DotNETRuntime_2_payload(buf):
	ret = {}
	ret['Count'] = read_win_type(buf, 'win:UInt32')
	ret['Depth'] = read_win_type(buf, 'win:UInt32')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_3_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_4_payload(buf):
	ret = {}
	ret['GenerationSize0'] = read_win_type(buf, 'win:UInt64')
	ret['TotalPromotedSize0'] = read_win_type(buf, 'win:UInt64')
	ret['GenerationSize1'] = read_win_type(buf, 'win:UInt64')
	ret['TotalPromotedSize1'] = read_win_type(buf, 'win:UInt64')
	ret['GenerationSize2'] = read_win_type(buf, 'win:UInt64')
	ret['TotalPromotedSize2'] = read_win_type(buf, 'win:UInt64')
	ret['GenerationSize3'] = read_win_type(buf, 'win:UInt64')
	ret['TotalPromotedSize3'] = read_win_type(buf, 'win:UInt64')
	ret['FinalizationPromotedSize'] = read_win_type(buf, 'win:UInt64')
	ret['FinalizationPromotedCount'] = read_win_type(buf, 'win:UInt64')
	ret['PinnedObjectCount'] = read_win_type(buf, 'win:UInt32')
	ret['SinkBlockCount'] = read_win_type(buf, 'win:UInt32')
	ret['GCHandleCount'] = read_win_type(buf, 'win:UInt32')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_5_payload(buf):
	ret = {}
	ret['Address'] = read_win_type(buf, 'win:UInt64')
	ret['Size'] = read_win_type(buf, 'win:UInt64')
	ret['Type'] = read_win_type(buf, 'win:UInt32')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_6_payload(buf):
	ret = {}
	ret['Address'] = read_win_type(buf, 'win:UInt64')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_7_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_8_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_9_payload(buf):
	ret = {}
	ret['Reason'] = read_win_type(buf, 'win:UInt32')
	ret['Count'] = read_win_type(buf, 'win:UInt32')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_10_payload(buf):
	ret = {}
	ret['AllocationAmount'] = read_win_type(buf, 'win:UInt32')
	ret['AllocationKind'] = read_win_type(buf, 'win:UInt32')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')
	ret['AllocationAmount64'] = read_win_type(buf, 'win:UInt64')
	ret['TypeID'] = read_win_type(buf, 'win:Pointer')
	ret['TypeName'] = read_win_type(buf, 'win:UnicodeString')
	ret['HeapIndex'] = read_win_type(buf, 'win:UInt32')
	ret['Address'] = read_win_type(buf, 'win:Pointer')

def read_Microsoft_Windows_DotNETRuntime_11_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_12_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_13_payload(buf):
	ret = {}
	ret['Count'] = read_win_type(buf, 'win:UInt32')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_14_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_15_payload(buf):
	ret = {}
	ret['Count'] = read_win_type(buf, 'win:UInt32')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_16_payload(buf):
	ret = {}
	ret['Index'] = read_win_type(buf, 'win:UInt32')
	ret['Count'] = read_win_type(buf, 'win:UInt32')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_17_payload(buf):
	ret = {}
	ret['Index'] = read_win_type(buf, 'win:UInt32')
	ret['Count'] = read_win_type(buf, 'win:UInt32')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_18_payload(buf):
	ret = {}
	ret['Index'] = read_win_type(buf, 'win:UInt32')
	ret['Count'] = read_win_type(buf, 'win:UInt32')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_19_payload(buf):
	ret = {}
	ret['Index'] = read_win_type(buf, 'win:UInt32')
	ret['Count'] = read_win_type(buf, 'win:UInt32')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_20_payload(buf):
	ret = {}
	ret['Address'] = read_win_type(buf, 'win:Pointer')
	ret['TypeID'] = read_win_type(buf, 'win:Pointer')
	ret['ObjectCountForTypeSample'] = read_win_type(buf, 'win:UInt32')
	ret['TotalSizeForTypeSample'] = read_win_type(buf, 'win:UInt64')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_21_payload(buf):
	ret = {}
	ret['Index'] = read_win_type(buf, 'win:UInt32')
	ret['Count'] = read_win_type(buf, 'win:UInt32')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_22_payload(buf):
	ret = {}
	ret['Index'] = read_win_type(buf, 'win:UInt32')
	ret['Count'] = read_win_type(buf, 'win:UInt32')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_23_payload(buf):
	ret = {}
	ret['Generation'] = read_win_type(buf, 'win:UInt8')
	ret['RangeStart'] = read_win_type(buf, 'win:Pointer')
	ret['RangeUsedLength'] = read_win_type(buf, 'win:UInt64')
	ret['RangeReservedLength'] = read_win_type(buf, 'win:UInt64')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_25_payload(buf):
	ret = {}
	ret['HeapNum'] = read_win_type(buf, 'win:UInt32')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_26_payload(buf):
	ret = {}
	ret['HeapNum'] = read_win_type(buf, 'win:UInt32')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_27_payload(buf):
	ret = {}
	ret['HeapNum'] = read_win_type(buf, 'win:UInt32')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_28_payload(buf):
	ret = {}
	ret['HeapNum'] = read_win_type(buf, 'win:UInt32')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_29_payload(buf):
	ret = {}
	ret['TypeID'] = read_win_type(buf, 'win:Pointer')
	ret['ObjectID'] = read_win_type(buf, 'win:Pointer')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_30_payload(buf):
	ret = {}
	ret['HandleID'] = read_win_type(buf, 'win:Pointer')
	ret['ObjectID'] = read_win_type(buf, 'win:Pointer')
	ret['Kind'] = read_win_type(buf, 'win:UInt32')
	ret['Generation'] = read_win_type(buf, 'win:UInt32')
	ret['AppDomainID'] = read_win_type(buf, 'win:UInt64')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_31_payload(buf):
	ret = {}
	ret['HandleID'] = read_win_type(buf, 'win:Pointer')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_32_payload(buf):
	ret = {}
	ret['Address'] = read_win_type(buf, 'win:Pointer')
	ret['TypeID'] = read_win_type(buf, 'win:Pointer')
	ret['ObjectCountForTypeSample'] = read_win_type(buf, 'win:UInt32')
	ret['TotalSizeForTypeSample'] = read_win_type(buf, 'win:UInt64')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_33_payload(buf):
	ret = {}
	ret['HandleID'] = read_win_type(buf, 'win:Pointer')
	ret['ObjectID'] = read_win_type(buf, 'win:Pointer')
	ret['ObjectSize'] = read_win_type(buf, 'win:UInt64')
	ret['TypeName'] = read_win_type(buf, 'win:UnicodeString')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_35_payload(buf):
	ret = {}
	ret['Reason'] = read_win_type(buf, 'win:UInt32')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_36_payload(buf):
	ret = {}
	ret['Count'] = read_win_type(buf, 'win:UInt32')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_37_payload(buf):
	ret = {}
	ret['Count'] = read_win_type(buf, 'win:UInt32')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_38_payload(buf):
	ret = {}
	ret['Count'] = read_win_type(buf, 'win:UInt32')
	ret['AppDomainID'] = read_win_type(buf, 'win:UInt64')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_40_payload(buf):
	ret = {}
	ret['WorkerThreadCount'] = read_win_type(buf, 'win:UInt32')
	ret['RetiredWorkerThreads'] = read_win_type(buf, 'win:UInt32')

def read_Microsoft_Windows_DotNETRuntime_41_payload(buf):
	ret = {}
	ret['WorkerThreadCount'] = read_win_type(buf, 'win:UInt32')
	ret['RetiredWorkerThreads'] = read_win_type(buf, 'win:UInt32')

def read_Microsoft_Windows_DotNETRuntime_42_payload(buf):
	ret = {}
	ret['WorkerThreadCount'] = read_win_type(buf, 'win:UInt32')
	ret['RetiredWorkerThreads'] = read_win_type(buf, 'win:UInt32')

def read_Microsoft_Windows_DotNETRuntime_43_payload(buf):
	ret = {}
	ret['WorkerThreadCount'] = read_win_type(buf, 'win:UInt32')
	ret['RetiredWorkerThreads'] = read_win_type(buf, 'win:UInt32')

def read_Microsoft_Windows_DotNETRuntime_44_payload(buf):
	ret = {}
	ret['IOThreadCount'] = read_win_type(buf, 'win:UInt32')
	ret['RetiredIOThreads'] = read_win_type(buf, 'win:UInt32')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_45_payload(buf):
	ret = {}
	ret['IOThreadCount'] = read_win_type(buf, 'win:UInt32')
	ret['RetiredIOThreads'] = read_win_type(buf, 'win:UInt32')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_46_payload(buf):
	ret = {}
	ret['IOThreadCount'] = read_win_type(buf, 'win:UInt32')
	ret['RetiredIOThreads'] = read_win_type(buf, 'win:UInt32')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_47_payload(buf):
	ret = {}
	ret['IOThreadCount'] = read_win_type(buf, 'win:UInt32')
	ret['RetiredIOThreads'] = read_win_type(buf, 'win:UInt32')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_48_payload(buf):
	ret = {}
	ret['ClrThreadID'] = read_win_type(buf, 'win:UInt32')
	ret['CpuUtilization'] = read_win_type(buf, 'win:UInt32')

def read_Microsoft_Windows_DotNETRuntime_49_payload(buf):
	ret = {}
	ret['ClrThreadID'] = read_win_type(buf, 'win:UInt32')
	ret['CpuUtilization'] = read_win_type(buf, 'win:UInt32')

def read_Microsoft_Windows_DotNETRuntime_50_payload(buf):
	ret = {}
	ret['ActiveWorkerThreadCount'] = read_win_type(buf, 'win:UInt32')
	ret['RetiredWorkerThreadCount'] = read_win_type(buf, 'win:UInt32')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_51_payload(buf):
	ret = {}
	ret['ActiveWorkerThreadCount'] = read_win_type(buf, 'win:UInt32')
	ret['RetiredWorkerThreadCount'] = read_win_type(buf, 'win:UInt32')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_52_payload(buf):
	ret = {}
	ret['ActiveWorkerThreadCount'] = read_win_type(buf, 'win:UInt32')
	ret['RetiredWorkerThreadCount'] = read_win_type(buf, 'win:UInt32')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_53_payload(buf):
	ret = {}
	ret['ActiveWorkerThreadCount'] = read_win_type(buf, 'win:UInt32')
	ret['RetiredWorkerThreadCount'] = read_win_type(buf, 'win:UInt32')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_54_payload(buf):
	ret = {}
	ret['Throughput'] = read_win_type(buf, 'win:Double')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_55_payload(buf):
	ret = {}
	ret['AverageThroughput'] = read_win_type(buf, 'win:Double')
	ret['NewWorkerThreadCount'] = read_win_type(buf, 'win:UInt32')
	ret['Reason'] = read_win_type(buf, 'win:UInt32')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_56_payload(buf):
	ret = {}
	ret['Duration'] = read_win_type(buf, 'win:Double')
	ret['Throughput'] = read_win_type(buf, 'win:Double')
	ret['ThreadWave'] = read_win_type(buf, 'win:Double')
	ret['ThroughputWave'] = read_win_type(buf, 'win:Double')
	ret['ThroughputErrorEstimate'] = read_win_type(buf, 'win:Double')
	ret['AverageThroughputErrorEstimate'] = read_win_type(buf, 'win:Double')
	ret['ThroughputRatio'] = read_win_type(buf, 'win:Double')
	ret['Confidence'] = read_win_type(buf, 'win:Double')
	ret['NewControlSetting'] = read_win_type(buf, 'win:Double')
	ret['NewThreadWaveMagnitude'] = read_win_type(buf, 'win:UInt16')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_57_payload(buf):
	ret = {}
	ret['ActiveWorkerThreadCount'] = read_win_type(buf, 'win:UInt32')
	ret['RetiredWorkerThreadCount'] = read_win_type(buf, 'win:UInt32')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_60_payload(buf):
	ret = {}
	ret['Count'] = read_win_type(buf, 'win:UInt32')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_61_payload(buf):
	ret = {}
	ret['WorkID'] = read_win_type(buf, 'win:Pointer')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_62_payload(buf):
	ret = {}
	ret['WorkID'] = read_win_type(buf, 'win:Pointer')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_63_payload(buf):
	ret = {}
	ret['NativeOverlapped'] = read_win_type(buf, 'win:Pointer')
	ret['Overlapped'] = read_win_type(buf, 'win:Pointer')
	ret['MultiDequeues'] = read_win_type(buf, 'win:Boolean')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_64_payload(buf):
	ret = {}
	ret['NativeOverlapped'] = read_win_type(buf, 'win:Pointer')
	ret['Overlapped'] = read_win_type(buf, 'win:Pointer')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_65_payload(buf):
	ret = {}
	ret['NativeOverlapped'] = read_win_type(buf, 'win:Pointer')
	ret['Overlapped'] = read_win_type(buf, 'win:Pointer')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_70_payload(buf):
	ret = {}
	ret['ID'] = read_win_type(buf, 'win:Pointer')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_71_payload(buf):
	ret = {}
	ret['ID'] = read_win_type(buf, 'win:Pointer')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_80_payload(buf):
	ret = {}
	ret['ExceptionType'] = read_win_type(buf, 'win:UnicodeString')
	ret['ExceptionMessage'] = read_win_type(buf, 'win:UnicodeString')
	ret['ExceptionEIP'] = read_win_type(buf, 'win:Pointer')
	ret['ExceptionHRESULT'] = read_win_type(buf, 'win:UInt32')
	ret['ExceptionFlags'] = read_win_type(buf, 'win:UInt16')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_81_payload(buf):
	ret = {}
	ret['ContentionFlags'] = read_win_type(buf, 'win:UInt8')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_91_payload(buf):
	ret = {}
	ret['ContentionFlags'] = read_win_type(buf, 'win:UInt8')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_82_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')
	ret['Reserved1'] = read_win_type(buf, 'win:UInt8')
	ret['Reserved2'] = read_win_type(buf, 'win:UInt8')
	ret['FrameCount'] = read_win_type(buf, 'win:UInt32')
	ret['Stack'] = read_win_type(buf, 'win:Pointer')

def read_Microsoft_Windows_DotNETRuntime_83_payload(buf):
	ret = {}
	ret['AppDomainID'] = read_win_type(buf, 'win:UInt64')
	ret['Allocated'] = read_win_type(buf, 'win:UInt64')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_84_payload(buf):
	ret = {}
	ret['AppDomainID'] = read_win_type(buf, 'win:UInt64')
	ret['Survived'] = read_win_type(buf, 'win:UInt64')
	ret['ProcessSurvived'] = read_win_type(buf, 'win:UInt64')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_85_payload(buf):
	ret = {}
	ret['ManagedThreadID'] = read_win_type(buf, 'win:UInt64')
	ret['AppDomainID'] = read_win_type(buf, 'win:UInt64')
	ret['Flags'] = read_win_type(buf, 'win:UInt32')
	ret['ManagedThreadIndex'] = read_win_type(buf, 'win:UInt32')
	ret['OSThreadID'] = read_win_type(buf, 'win:UInt32')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_86_payload(buf):
	ret = {}
	ret['ManagedThreadID'] = read_win_type(buf, 'win:UInt64')
	ret['AppDomainID'] = read_win_type(buf, 'win:UInt64')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_87_payload(buf):
	ret = {}
	ret['ManagedThreadID'] = read_win_type(buf, 'win:UInt64')
	ret['AppDomainID'] = read_win_type(buf, 'win:UInt64')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_88_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')
	ret['ModuleID'] = read_win_type(buf, 'win:UInt64')
	ret['StubMethodID'] = read_win_type(buf, 'win:UInt64')
	ret['StubFlags'] = read_win_type(buf, 'win:UInt32')
	ret['ManagedInteropMethodToken'] = read_win_type(buf, 'win:UInt32')
	ret['ManagedInteropMethodNamespace'] = read_win_type(buf, 'win:UnicodeString')
	ret['ManagedInteropMethodName'] = read_win_type(buf, 'win:UnicodeString')
	ret['ManagedInteropMethodSignature'] = read_win_type(buf, 'win:UnicodeString')
	ret['NativeMethodSignature'] = read_win_type(buf, 'win:UnicodeString')
	ret['StubMethodSignature'] = read_win_type(buf, 'win:UnicodeString')
	ret['StubMethodILCode'] = read_win_type(buf, 'win:UnicodeString')

def read_Microsoft_Windows_DotNETRuntime_89_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')
	ret['ModuleID'] = read_win_type(buf, 'win:UInt64')
	ret['StubMethodID'] = read_win_type(buf, 'win:UInt64')
	ret['ManagedInteropMethodToken'] = read_win_type(buf, 'win:UInt32')
	ret['ManagedInteropMethodNamespace'] = read_win_type(buf, 'win:UnicodeString')
	ret['ManagedInteropMethodName'] = read_win_type(buf, 'win:UnicodeString')
	ret['ManagedInteropMethodSignature'] = read_win_type(buf, 'win:UnicodeString')

def read_Microsoft_Windows_DotNETRuntime_137_payload(buf):
	ret = {}
	ret['MethodID'] = read_win_type(buf, 'win:UInt64')
	ret['ModuleID'] = read_win_type(buf, 'win:UInt64')
	ret['MethodStartAddress'] = read_win_type(buf, 'win:UInt64')
	ret['MethodSize'] = read_win_type(buf, 'win:UInt32')
	ret['MethodToken'] = read_win_type(buf, 'win:UInt32')
	ret['MethodFlags'] = read_win_type(buf, 'win:UInt32')

def read_Microsoft_Windows_DotNETRuntime_138_payload(buf):
	ret = {}
	ret['MethodID'] = read_win_type(buf, 'win:UInt64')
	ret['ModuleID'] = read_win_type(buf, 'win:UInt64')
	ret['MethodStartAddress'] = read_win_type(buf, 'win:UInt64')
	ret['MethodSize'] = read_win_type(buf, 'win:UInt32')
	ret['MethodToken'] = read_win_type(buf, 'win:UInt32')
	ret['MethodFlags'] = read_win_type(buf, 'win:UInt32')

def read_Microsoft_Windows_DotNETRuntime_139_payload(buf):
	ret = {}
	ret['MethodID'] = read_win_type(buf, 'win:UInt64')
	ret['ModuleID'] = read_win_type(buf, 'win:UInt64')
	ret['MethodStartAddress'] = read_win_type(buf, 'win:UInt64')
	ret['MethodSize'] = read_win_type(buf, 'win:UInt32')
	ret['MethodToken'] = read_win_type(buf, 'win:UInt32')
	ret['MethodFlags'] = read_win_type(buf, 'win:UInt32')
	ret['MethodNamespace'] = read_win_type(buf, 'win:UnicodeString')
	ret['MethodName'] = read_win_type(buf, 'win:UnicodeString')
	ret['MethodSignature'] = read_win_type(buf, 'win:UnicodeString')

def read_Microsoft_Windows_DotNETRuntime_140_payload(buf):
	ret = {}
	ret['MethodID'] = read_win_type(buf, 'win:UInt64')
	ret['ModuleID'] = read_win_type(buf, 'win:UInt64')
	ret['MethodStartAddress'] = read_win_type(buf, 'win:UInt64')
	ret['MethodSize'] = read_win_type(buf, 'win:UInt32')
	ret['MethodToken'] = read_win_type(buf, 'win:UInt32')
	ret['MethodFlags'] = read_win_type(buf, 'win:UInt32')
	ret['MethodNamespace'] = read_win_type(buf, 'win:UnicodeString')
	ret['MethodName'] = read_win_type(buf, 'win:UnicodeString')
	ret['MethodSignature'] = read_win_type(buf, 'win:UnicodeString')

def read_Microsoft_Windows_DotNETRuntime_141_payload(buf):
	ret = {}
	ret['MethodID'] = read_win_type(buf, 'win:UInt64')
	ret['ModuleID'] = read_win_type(buf, 'win:UInt64')
	ret['MethodStartAddress'] = read_win_type(buf, 'win:UInt64')
	ret['MethodSize'] = read_win_type(buf, 'win:UInt32')
	ret['MethodToken'] = read_win_type(buf, 'win:UInt32')
	ret['MethodFlags'] = read_win_type(buf, 'win:UInt32')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')
	ret['ReJITID'] = read_win_type(buf, 'win:UInt64')

def read_Microsoft_Windows_DotNETRuntime_142_payload(buf):
	ret = {}
	ret['MethodID'] = read_win_type(buf, 'win:UInt64')
	ret['ModuleID'] = read_win_type(buf, 'win:UInt64')
	ret['MethodStartAddress'] = read_win_type(buf, 'win:UInt64')
	ret['MethodSize'] = read_win_type(buf, 'win:UInt32')
	ret['MethodToken'] = read_win_type(buf, 'win:UInt32')
	ret['MethodFlags'] = read_win_type(buf, 'win:UInt32')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')
	ret['ReJITID'] = read_win_type(buf, 'win:UInt64')

def read_Microsoft_Windows_DotNETRuntime_143_payload(buf):
	ret = {}
	ret['MethodID'] = read_win_type(buf, 'win:UInt64')
	ret['ModuleID'] = read_win_type(buf, 'win:UInt64')
	ret['MethodStartAddress'] = read_win_type(buf, 'win:UInt64')
	ret['MethodSize'] = read_win_type(buf, 'win:UInt32')
	ret['MethodToken'] = read_win_type(buf, 'win:UInt32')
	ret['MethodFlags'] = read_win_type(buf, 'win:UInt32')
	ret['MethodNamespace'] = read_win_type(buf, 'win:UnicodeString')
	ret['MethodName'] = read_win_type(buf, 'win:UnicodeString')
	ret['MethodSignature'] = read_win_type(buf, 'win:UnicodeString')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')
	ret['ReJITID'] = read_win_type(buf, 'win:UInt64')

def read_Microsoft_Windows_DotNETRuntime_144_payload(buf):
	ret = {}
	ret['MethodID'] = read_win_type(buf, 'win:UInt64')
	ret['ModuleID'] = read_win_type(buf, 'win:UInt64')
	ret['MethodStartAddress'] = read_win_type(buf, 'win:UInt64')
	ret['MethodSize'] = read_win_type(buf, 'win:UInt32')
	ret['MethodToken'] = read_win_type(buf, 'win:UInt32')
	ret['MethodFlags'] = read_win_type(buf, 'win:UInt32')
	ret['MethodNamespace'] = read_win_type(buf, 'win:UnicodeString')
	ret['MethodName'] = read_win_type(buf, 'win:UnicodeString')
	ret['MethodSignature'] = read_win_type(buf, 'win:UnicodeString')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')
	ret['ReJITID'] = read_win_type(buf, 'win:UInt64')

def read_Microsoft_Windows_DotNETRuntime_145_payload(buf):
	ret = {}
	ret['MethodID'] = read_win_type(buf, 'win:UInt64')
	ret['ModuleID'] = read_win_type(buf, 'win:UInt64')
	ret['MethodToken'] = read_win_type(buf, 'win:UInt32')
	ret['MethodILSize'] = read_win_type(buf, 'win:UInt32')
	ret['MethodNamespace'] = read_win_type(buf, 'win:UnicodeString')
	ret['MethodName'] = read_win_type(buf, 'win:UnicodeString')
	ret['MethodSignature'] = read_win_type(buf, 'win:UnicodeString')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_185_payload(buf):
	ret = {}
	ret['MethodBeingCompiledNamespace'] = read_win_type(buf, 'win:UnicodeString')
	ret['MethodBeingCompiledName'] = read_win_type(buf, 'win:UnicodeString')
	ret['MethodBeingCompiledNameSignature'] = read_win_type(buf, 'win:UnicodeString')
	ret['InlinerNamespace'] = read_win_type(buf, 'win:UnicodeString')
	ret['InlinerName'] = read_win_type(buf, 'win:UnicodeString')
	ret['InlinerNameSignature'] = read_win_type(buf, 'win:UnicodeString')
	ret['InlineeNamespace'] = read_win_type(buf, 'win:UnicodeString')
	ret['InlineeName'] = read_win_type(buf, 'win:UnicodeString')
	ret['InlineeNameSignature'] = read_win_type(buf, 'win:UnicodeString')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_186_payload(buf):
	ret = {}
	ret['MethodBeingCompiledNamespace'] = read_win_type(buf, 'win:UnicodeString')
	ret['MethodBeingCompiledName'] = read_win_type(buf, 'win:UnicodeString')
	ret['MethodBeingCompiledNameSignature'] = read_win_type(buf, 'win:UnicodeString')
	ret['InlinerNamespace'] = read_win_type(buf, 'win:UnicodeString')
	ret['InlinerName'] = read_win_type(buf, 'win:UnicodeString')
	ret['InlinerNameSignature'] = read_win_type(buf, 'win:UnicodeString')
	ret['InlineeNamespace'] = read_win_type(buf, 'win:UnicodeString')
	ret['InlineeName'] = read_win_type(buf, 'win:UnicodeString')
	ret['InlineeNameSignature'] = read_win_type(buf, 'win:UnicodeString')
	ret['FailAlways'] = read_win_type(buf, 'win:Boolean')
	ret['FailReason'] = read_win_type(buf, 'win:AnsiString')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_188_payload(buf):
	ret = {}
	ret['MethodBeingCompiledNamespace'] = read_win_type(buf, 'win:UnicodeString')
	ret['MethodBeingCompiledName'] = read_win_type(buf, 'win:UnicodeString')
	ret['MethodBeingCompiledNameSignature'] = read_win_type(buf, 'win:UnicodeString')
	ret['CallerNamespace'] = read_win_type(buf, 'win:UnicodeString')
	ret['CallerName'] = read_win_type(buf, 'win:UnicodeString')
	ret['CallerNameSignature'] = read_win_type(buf, 'win:UnicodeString')
	ret['CalleeNamespace'] = read_win_type(buf, 'win:UnicodeString')
	ret['CalleeName'] = read_win_type(buf, 'win:UnicodeString')
	ret['CalleeNameSignature'] = read_win_type(buf, 'win:UnicodeString')
	ret['TailPrefix'] = read_win_type(buf, 'win:Boolean')
	ret['TailCallType'] = read_win_type(buf, 'win:UInt32')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_189_payload(buf):
	ret = {}
	ret['MethodBeingCompiledNamespace'] = read_win_type(buf, 'win:UnicodeString')
	ret['MethodBeingCompiledName'] = read_win_type(buf, 'win:UnicodeString')
	ret['MethodBeingCompiledNameSignature'] = read_win_type(buf, 'win:UnicodeString')
	ret['CallerNamespace'] = read_win_type(buf, 'win:UnicodeString')
	ret['CallerName'] = read_win_type(buf, 'win:UnicodeString')
	ret['CallerNameSignature'] = read_win_type(buf, 'win:UnicodeString')
	ret['CalleeNamespace'] = read_win_type(buf, 'win:UnicodeString')
	ret['CalleeName'] = read_win_type(buf, 'win:UnicodeString')
	ret['CalleeNameSignature'] = read_win_type(buf, 'win:UnicodeString')
	ret['TailPrefix'] = read_win_type(buf, 'win:Boolean')
	ret['FailReason'] = read_win_type(buf, 'win:AnsiString')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_190_payload(buf):
	ret = {}
	ret['MethodID'] = read_win_type(buf, 'win:UInt64')
	ret['ReJITID'] = read_win_type(buf, 'win:UInt64')
	ret['MethodExtent'] = read_win_type(buf, 'win:UInt8')
	ret['CountOfMapEntries'] = read_win_type(buf, 'win:UInt16')
	ret['ILOffsets'] = read_win_type(buf, 'win:UInt32')
	ret['NativeOffsets'] = read_win_type(buf, 'win:UInt32')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_149_payload(buf):
	ret = {}
	ret['ModuleID'] = read_win_type(buf, 'win:UInt64')
	ret['AssemblyID'] = read_win_type(buf, 'win:UInt64')
	ret['ModuleFlags'] = read_win_type(buf, 'win:UInt32')
	ret['Reserved1'] = read_win_type(buf, 'win:UInt32')
	ret['ModuleILPath'] = read_win_type(buf, 'win:UnicodeString')
	ret['ModuleNativePath'] = read_win_type(buf, 'win:UnicodeString')

def read_Microsoft_Windows_DotNETRuntime_150_payload(buf):
	ret = {}
	ret['ModuleID'] = read_win_type(buf, 'win:UInt64')
	ret['AssemblyID'] = read_win_type(buf, 'win:UInt64')
	ret['ModuleFlags'] = read_win_type(buf, 'win:UInt32')
	ret['Reserved1'] = read_win_type(buf, 'win:UInt32')
	ret['ModuleILPath'] = read_win_type(buf, 'win:UnicodeString')
	ret['ModuleNativePath'] = read_win_type(buf, 'win:UnicodeString')

def read_Microsoft_Windows_DotNETRuntime_151_payload(buf):
	ret = {}
	ret['ModuleID'] = read_win_type(buf, 'win:UInt64')
	ret['AssemblyID'] = read_win_type(buf, 'win:UInt64')
	ret['AppDomainID'] = read_win_type(buf, 'win:UInt64')
	ret['ModuleFlags'] = read_win_type(buf, 'win:UInt32')
	ret['Reserved1'] = read_win_type(buf, 'win:UInt32')
	ret['ModuleILPath'] = read_win_type(buf, 'win:UnicodeString')
	ret['ModuleNativePath'] = read_win_type(buf, 'win:UnicodeString')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_152_payload(buf):
	ret = {}
	ret['ModuleID'] = read_win_type(buf, 'win:UInt64')
	ret['AssemblyID'] = read_win_type(buf, 'win:UInt64')
	ret['ModuleFlags'] = read_win_type(buf, 'win:UInt32')
	ret['Reserved1'] = read_win_type(buf, 'win:UInt32')
	ret['ModuleILPath'] = read_win_type(buf, 'win:UnicodeString')
	ret['ModuleNativePath'] = read_win_type(buf, 'win:UnicodeString')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')
	ret['ManagedPdbSignature'] = read_win_type(buf, 'win:GUID')
	ret['ManagedPdbAge'] = read_win_type(buf, 'win:UInt32')
	ret['ManagedPdbBuildPath'] = read_win_type(buf, 'win:UnicodeString')
	ret['NativePdbSignature'] = read_win_type(buf, 'win:GUID')
	ret['NativePdbAge'] = read_win_type(buf, 'win:UInt32')
	ret['NativePdbBuildPath'] = read_win_type(buf, 'win:UnicodeString')

def read_Microsoft_Windows_DotNETRuntime_153_payload(buf):
	ret = {}
	ret['ModuleID'] = read_win_type(buf, 'win:UInt64')
	ret['AssemblyID'] = read_win_type(buf, 'win:UInt64')
	ret['ModuleFlags'] = read_win_type(buf, 'win:UInt32')
	ret['Reserved1'] = read_win_type(buf, 'win:UInt32')
	ret['ModuleILPath'] = read_win_type(buf, 'win:UnicodeString')
	ret['ModuleNativePath'] = read_win_type(buf, 'win:UnicodeString')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')
	ret['ManagedPdbSignature'] = read_win_type(buf, 'win:GUID')
	ret['ManagedPdbAge'] = read_win_type(buf, 'win:UInt32')
	ret['ManagedPdbBuildPath'] = read_win_type(buf, 'win:UnicodeString')
	ret['NativePdbSignature'] = read_win_type(buf, 'win:GUID')
	ret['NativePdbAge'] = read_win_type(buf, 'win:UInt32')
	ret['NativePdbBuildPath'] = read_win_type(buf, 'win:UnicodeString')

def read_Microsoft_Windows_DotNETRuntime_154_payload(buf):
	ret = {}
	ret['AssemblyID'] = read_win_type(buf, 'win:UInt64')
	ret['AppDomainID'] = read_win_type(buf, 'win:UInt64')
	ret['BindingID'] = read_win_type(buf, 'win:UInt64')
	ret['AssemblyFlags'] = read_win_type(buf, 'win:UInt32')
	ret['FullyQualifiedAssemblyName'] = read_win_type(buf, 'win:UnicodeString')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_155_payload(buf):
	ret = {}
	ret['AssemblyID'] = read_win_type(buf, 'win:UInt64')
	ret['AppDomainID'] = read_win_type(buf, 'win:UInt64')
	ret['BindingID'] = read_win_type(buf, 'win:UInt64')
	ret['AssemblyFlags'] = read_win_type(buf, 'win:UInt32')
	ret['FullyQualifiedAssemblyName'] = read_win_type(buf, 'win:UnicodeString')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_156_payload(buf):
	ret = {}
	ret['AppDomainID'] = read_win_type(buf, 'win:UInt64')
	ret['AppDomainFlags'] = read_win_type(buf, 'win:UInt32')
	ret['AppDomainName'] = read_win_type(buf, 'win:UnicodeString')
	ret['AppDomainIndex'] = read_win_type(buf, 'win:UInt32')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_157_payload(buf):
	ret = {}
	ret['AppDomainID'] = read_win_type(buf, 'win:UInt64')
	ret['AppDomainFlags'] = read_win_type(buf, 'win:UInt32')
	ret['AppDomainName'] = read_win_type(buf, 'win:UnicodeString')
	ret['AppDomainIndex'] = read_win_type(buf, 'win:UInt32')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_158_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')
	ret['ModuleID'] = read_win_type(buf, 'win:UInt64')
	ret['RangeBegin'] = read_win_type(buf, 'win:UInt32')
	ret['RangeSize'] = read_win_type(buf, 'win:UInt32')
	ret['RangeType'] = read_win_type(buf, 'win:UInt8')

def read_Microsoft_Windows_DotNETRuntime_181_payload(buf):
	ret = {}
	ret['VerificationFlags'] = read_win_type(buf, 'win:UInt32')
	ret['ErrorCode'] = read_win_type(buf, 'win:UInt32')
	ret['FullyQualifiedAssemblyName'] = read_win_type(buf, 'win:UnicodeString')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_182_payload(buf):
	ret = {}
	ret['VerificationFlags'] = read_win_type(buf, 'win:UInt32')
	ret['ErrorCode'] = read_win_type(buf, 'win:UInt32')
	ret['FullyQualifiedAssemblyName'] = read_win_type(buf, 'win:UnicodeString')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_183_payload(buf):
	ret = {}
	ret['VerificationFlags'] = read_win_type(buf, 'win:UInt32')
	ret['ErrorCode'] = read_win_type(buf, 'win:UInt32')
	ret['ModulePath'] = read_win_type(buf, 'win:UnicodeString')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_184_payload(buf):
	ret = {}
	ret['VerificationFlags'] = read_win_type(buf, 'win:UInt32')
	ret['ErrorCode'] = read_win_type(buf, 'win:UInt32')
	ret['ModulePath'] = read_win_type(buf, 'win:UnicodeString')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_187_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')
	ret['Sku'] = read_win_type(buf, 'win:UInt16')
	ret['BclMajorVersion'] = read_win_type(buf, 'win:UInt16')
	ret['BclMinorVersion'] = read_win_type(buf, 'win:UInt16')
	ret['BclBuildNumber'] = read_win_type(buf, 'win:UInt16')
	ret['BclQfeNumber'] = read_win_type(buf, 'win:UInt16')
	ret['VMMajorVersion'] = read_win_type(buf, 'win:UInt16')
	ret['VMMinorVersion'] = read_win_type(buf, 'win:UInt16')
	ret['VMBuildNumber'] = read_win_type(buf, 'win:UInt16')
	ret['VMQfeNumber'] = read_win_type(buf, 'win:UInt16')
	ret['StartupFlags'] = read_win_type(buf, 'win:UInt32')
	ret['StartupMode'] = read_win_type(buf, 'win:UInt8')
	ret['CommandLine'] = read_win_type(buf, 'win:UnicodeString')
	ret['ComObjectGuid'] = read_win_type(buf, 'win:GUID')
	ret['RuntimeDllPath'] = read_win_type(buf, 'win:UnicodeString')

def read_Microsoft_Windows_DotNETRuntime_200_payload(buf):
	ret = {}
	ret['BytesAllocated'] = read_win_type(buf, 'win:UInt64')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntime_201_payload(buf):
	ret = {}
	ret['BytesFreed'] = read_win_type(buf, 'win:UInt64')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimeRundown_0_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')
	ret['Reserved1'] = read_win_type(buf, 'win:UInt8')
	ret['Reserved2'] = read_win_type(buf, 'win:UInt8')
	ret['FrameCount'] = read_win_type(buf, 'win:UInt32')
	ret['Stack'] = read_win_type(buf, 'win:Pointer')

def read_Microsoft_Windows_DotNETRuntimeRundown_141_payload(buf):
	ret = {}
	ret['MethodID'] = read_win_type(buf, 'win:UInt64')
	ret['ModuleID'] = read_win_type(buf, 'win:UInt64')
	ret['MethodStartAddress'] = read_win_type(buf, 'win:UInt64')
	ret['MethodSize'] = read_win_type(buf, 'win:UInt32')
	ret['MethodToken'] = read_win_type(buf, 'win:UInt32')
	ret['MethodFlags'] = read_win_type(buf, 'win:UInt32')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')
	ret['ReJITID'] = read_win_type(buf, 'win:UInt64')

def read_Microsoft_Windows_DotNETRuntimeRundown_142_payload(buf):
	ret = {}
	ret['MethodID'] = read_win_type(buf, 'win:UInt64')
	ret['ModuleID'] = read_win_type(buf, 'win:UInt64')
	ret['MethodStartAddress'] = read_win_type(buf, 'win:UInt64')
	ret['MethodSize'] = read_win_type(buf, 'win:UInt32')
	ret['MethodToken'] = read_win_type(buf, 'win:UInt32')
	ret['MethodFlags'] = read_win_type(buf, 'win:UInt32')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')
	ret['ReJITID'] = read_win_type(buf, 'win:UInt64')

def read_Microsoft_Windows_DotNETRuntimeRundown_143_payload(buf):
	ret = {}
	ret['MethodID'] = read_win_type(buf, 'win:UInt64')
	ret['ModuleID'] = read_win_type(buf, 'win:UInt64')
	ret['MethodStartAddress'] = read_win_type(buf, 'win:UInt64')
	ret['MethodSize'] = read_win_type(buf, 'win:UInt32')
	ret['MethodToken'] = read_win_type(buf, 'win:UInt32')
	ret['MethodFlags'] = read_win_type(buf, 'win:UInt32')
	ret['MethodNamespace'] = read_win_type(buf, 'win:UnicodeString')
	ret['MethodName'] = read_win_type(buf, 'win:UnicodeString')
	ret['MethodSignature'] = read_win_type(buf, 'win:UnicodeString')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')
	ret['ReJITID'] = read_win_type(buf, 'win:UInt64')

def read_Microsoft_Windows_DotNETRuntimeRundown_144_payload(buf):
	ret = {}
	ret['MethodID'] = read_win_type(buf, 'win:UInt64')
	ret['ModuleID'] = read_win_type(buf, 'win:UInt64')
	ret['MethodStartAddress'] = read_win_type(buf, 'win:UInt64')
	ret['MethodSize'] = read_win_type(buf, 'win:UInt32')
	ret['MethodToken'] = read_win_type(buf, 'win:UInt32')
	ret['MethodFlags'] = read_win_type(buf, 'win:UInt32')
	ret['MethodNamespace'] = read_win_type(buf, 'win:UnicodeString')
	ret['MethodName'] = read_win_type(buf, 'win:UnicodeString')
	ret['MethodSignature'] = read_win_type(buf, 'win:UnicodeString')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')
	ret['ReJITID'] = read_win_type(buf, 'win:UInt64')

def read_Microsoft_Windows_DotNETRuntimeRundown_145_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimeRundown_146_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimeRundown_147_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimeRundown_148_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimeRundown_149_payload(buf):
	ret = {}
	ret['MethodID'] = read_win_type(buf, 'win:UInt64')
	ret['ReJITID'] = read_win_type(buf, 'win:UInt64')
	ret['MethodExtent'] = read_win_type(buf, 'win:UInt8')
	ret['CountOfMapEntries'] = read_win_type(buf, 'win:UInt16')
	ret['ILOffsets'] = read_win_type(buf, 'win:UInt32')
	ret['NativeOffsets'] = read_win_type(buf, 'win:UInt32')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimeRundown_150_payload(buf):
	ret = {}
	ret['MethodID'] = read_win_type(buf, 'win:UInt64')
	ret['ReJITID'] = read_win_type(buf, 'win:UInt64')
	ret['MethodExtent'] = read_win_type(buf, 'win:UInt8')
	ret['CountOfMapEntries'] = read_win_type(buf, 'win:UInt16')
	ret['ILOffsets'] = read_win_type(buf, 'win:UInt32')
	ret['NativeOffsets'] = read_win_type(buf, 'win:UInt32')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimeRundown_151_payload(buf):
	ret = {}
	ret['ModuleID'] = read_win_type(buf, 'win:UInt64')
	ret['AssemblyID'] = read_win_type(buf, 'win:UInt64')
	ret['AppDomainID'] = read_win_type(buf, 'win:UInt64')
	ret['ModuleFlags'] = read_win_type(buf, 'win:UInt32')
	ret['Reserved1'] = read_win_type(buf, 'win:UInt32')
	ret['ModuleILPath'] = read_win_type(buf, 'win:UnicodeString')
	ret['ModuleNativePath'] = read_win_type(buf, 'win:UnicodeString')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimeRundown_152_payload(buf):
	ret = {}
	ret['ModuleID'] = read_win_type(buf, 'win:UInt64')
	ret['AssemblyID'] = read_win_type(buf, 'win:UInt64')
	ret['AppDomainID'] = read_win_type(buf, 'win:UInt64')
	ret['ModuleFlags'] = read_win_type(buf, 'win:UInt32')
	ret['Reserved1'] = read_win_type(buf, 'win:UInt32')
	ret['ModuleILPath'] = read_win_type(buf, 'win:UnicodeString')
	ret['ModuleNativePath'] = read_win_type(buf, 'win:UnicodeString')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimeRundown_153_payload(buf):
	ret = {}
	ret['ModuleID'] = read_win_type(buf, 'win:UInt64')
	ret['AssemblyID'] = read_win_type(buf, 'win:UInt64')
	ret['ModuleFlags'] = read_win_type(buf, 'win:UInt32')
	ret['Reserved1'] = read_win_type(buf, 'win:UInt32')
	ret['ModuleILPath'] = read_win_type(buf, 'win:UnicodeString')
	ret['ModuleNativePath'] = read_win_type(buf, 'win:UnicodeString')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')
	ret['ManagedPdbSignature'] = read_win_type(buf, 'win:GUID')
	ret['ManagedPdbAge'] = read_win_type(buf, 'win:UInt32')
	ret['ManagedPdbBuildPath'] = read_win_type(buf, 'win:UnicodeString')
	ret['NativePdbSignature'] = read_win_type(buf, 'win:GUID')
	ret['NativePdbAge'] = read_win_type(buf, 'win:UInt32')
	ret['NativePdbBuildPath'] = read_win_type(buf, 'win:UnicodeString')

def read_Microsoft_Windows_DotNETRuntimeRundown_154_payload(buf):
	ret = {}
	ret['ModuleID'] = read_win_type(buf, 'win:UInt64')
	ret['AssemblyID'] = read_win_type(buf, 'win:UInt64')
	ret['ModuleFlags'] = read_win_type(buf, 'win:UInt32')
	ret['Reserved1'] = read_win_type(buf, 'win:UInt32')
	ret['ModuleILPath'] = read_win_type(buf, 'win:UnicodeString')
	ret['ModuleNativePath'] = read_win_type(buf, 'win:UnicodeString')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')
	ret['ManagedPdbSignature'] = read_win_type(buf, 'win:GUID')
	ret['ManagedPdbAge'] = read_win_type(buf, 'win:UInt32')
	ret['ManagedPdbBuildPath'] = read_win_type(buf, 'win:UnicodeString')
	ret['NativePdbSignature'] = read_win_type(buf, 'win:GUID')
	ret['NativePdbAge'] = read_win_type(buf, 'win:UInt32')
	ret['NativePdbBuildPath'] = read_win_type(buf, 'win:UnicodeString')

def read_Microsoft_Windows_DotNETRuntimeRundown_155_payload(buf):
	ret = {}
	ret['AssemblyID'] = read_win_type(buf, 'win:UInt64')
	ret['AppDomainID'] = read_win_type(buf, 'win:UInt64')
	ret['BindingID'] = read_win_type(buf, 'win:UInt64')
	ret['AssemblyFlags'] = read_win_type(buf, 'win:UInt32')
	ret['FullyQualifiedAssemblyName'] = read_win_type(buf, 'win:UnicodeString')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimeRundown_156_payload(buf):
	ret = {}
	ret['AssemblyID'] = read_win_type(buf, 'win:UInt64')
	ret['AppDomainID'] = read_win_type(buf, 'win:UInt64')
	ret['BindingID'] = read_win_type(buf, 'win:UInt64')
	ret['AssemblyFlags'] = read_win_type(buf, 'win:UInt32')
	ret['FullyQualifiedAssemblyName'] = read_win_type(buf, 'win:UnicodeString')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimeRundown_157_payload(buf):
	ret = {}
	ret['AppDomainID'] = read_win_type(buf, 'win:UInt64')
	ret['AppDomainFlags'] = read_win_type(buf, 'win:UInt32')
	ret['AppDomainName'] = read_win_type(buf, 'win:UnicodeString')
	ret['AppDomainIndex'] = read_win_type(buf, 'win:UInt32')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimeRundown_158_payload(buf):
	ret = {}
	ret['AppDomainID'] = read_win_type(buf, 'win:UInt64')
	ret['AppDomainFlags'] = read_win_type(buf, 'win:UInt32')
	ret['AppDomainName'] = read_win_type(buf, 'win:UnicodeString')
	ret['AppDomainIndex'] = read_win_type(buf, 'win:UInt32')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimeRundown_159_payload(buf):
	ret = {}
	ret['ManagedThreadID'] = read_win_type(buf, 'win:UInt64')
	ret['AppDomainID'] = read_win_type(buf, 'win:UInt64')
	ret['Flags'] = read_win_type(buf, 'win:UInt32')
	ret['ManagedThreadIndex'] = read_win_type(buf, 'win:UInt32')
	ret['OSThreadID'] = read_win_type(buf, 'win:UInt32')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimeRundown_160_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')
	ret['ModuleID'] = read_win_type(buf, 'win:UInt64')
	ret['RangeBegin'] = read_win_type(buf, 'win:UInt32')
	ret['RangeSize'] = read_win_type(buf, 'win:UInt32')
	ret['RangeType'] = read_win_type(buf, 'win:UInt8')

def read_Microsoft_Windows_DotNETRuntimeRundown_161_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')
	ret['ModuleID'] = read_win_type(buf, 'win:UInt64')
	ret['RangeBegin'] = read_win_type(buf, 'win:UInt32')
	ret['RangeSize'] = read_win_type(buf, 'win:UInt32')
	ret['RangeType'] = read_win_type(buf, 'win:UInt8')

def read_Microsoft_Windows_DotNETRuntimeRundown_187_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')
	ret['Sku'] = read_win_type(buf, 'win:UInt16')
	ret['BclMajorVersion'] = read_win_type(buf, 'win:UInt16')
	ret['BclMinorVersion'] = read_win_type(buf, 'win:UInt16')
	ret['BclBuildNumber'] = read_win_type(buf, 'win:UInt16')
	ret['BclQfeNumber'] = read_win_type(buf, 'win:UInt16')
	ret['VMMajorVersion'] = read_win_type(buf, 'win:UInt16')
	ret['VMMinorVersion'] = read_win_type(buf, 'win:UInt16')
	ret['VMBuildNumber'] = read_win_type(buf, 'win:UInt16')
	ret['VMQfeNumber'] = read_win_type(buf, 'win:UInt16')
	ret['StartupFlags'] = read_win_type(buf, 'win:UInt32')
	ret['StartupMode'] = read_win_type(buf, 'win:UInt8')
	ret['CommandLine'] = read_win_type(buf, 'win:UnicodeString')
	ret['ComObjectGuid'] = read_win_type(buf, 'win:GUID')
	ret['RuntimeDllPath'] = read_win_type(buf, 'win:UnicodeString')

def read_Microsoft_Windows_DotNETRuntimeStress_0_payload(buf):
	ret = {}
	ret['Facility'] = read_win_type(buf, 'win:UInt32')
	ret['LogLevel'] = read_win_type(buf, 'win:UInt8')
	ret['Message'] = read_win_type(buf, 'win:AnsiString')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimeStress_1_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')
	ret['Reserved1'] = read_win_type(buf, 'win:UInt8')
	ret['Reserved2'] = read_win_type(buf, 'win:UInt8')
	ret['FrameCount'] = read_win_type(buf, 'win:UInt32')
	ret['Stack'] = read_win_type(buf, 'win:Pointer')

def read_Microsoft_Windows_DotNETRuntimePrivate_1_payload(buf):
	ret = {}
	ret['DoCompact'] = read_win_type(buf, 'win:Boolean')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_2_payload(buf):
	ret = {}
	ret['SegmentSize'] = read_win_type(buf, 'win:UInt64')
	ret['LargeObjectSegmentSize'] = read_win_type(buf, 'win:UInt64')
	ret['ServerGC'] = read_win_type(buf, 'win:Boolean')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_3_payload(buf):
	ret = {}
	ret['DesiredAllocation'] = read_win_type(buf, 'win:UInt64')
	ret['NewAllocation'] = read_win_type(buf, 'win:UInt64')
	ret['GenerationNumber'] = read_win_type(buf, 'win:UInt32')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_4_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_5_payload(buf):
	ret = {}
	ret['FinalYoungestDesired'] = read_win_type(buf, 'win:UInt64')
	ret['NumHeaps'] = read_win_type(buf, 'win:Int32')
	ret['CondemnedGeneration'] = read_win_type(buf, 'win:UInt32')
	ret['Gen0ReductionCount'] = read_win_type(buf, 'win:UInt32')
	ret['Reason'] = read_win_type(buf, 'win:UInt32')
	ret['GlobalMechanisms'] = read_win_type(buf, 'win:UInt32')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_6_payload(buf):
	ret = {}
	ret['Heap'] = read_win_type(buf, 'win:UInt32')
	ret['JoinTime'] = read_win_type(buf, 'win:UInt32')
	ret['JoinType'] = read_win_type(buf, 'win:UInt32')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_7_payload(buf):
	ret = {}
	ret['HeapNum'] = read_win_type(buf, 'win:UInt32')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_8_payload(buf):
	ret = {}
	ret['HeapNum'] = read_win_type(buf, 'win:UInt32')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_9_payload(buf):
	ret = {}
	ret['HeapNum'] = read_win_type(buf, 'win:UInt32')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_10_payload(buf):
	ret = {}
	ret['HeapNum'] = read_win_type(buf, 'win:UInt32')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_11_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_12_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_13_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_14_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_15_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_16_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_17_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_18_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_19_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_20_payload(buf):
	ret = {}
	ret['Objects'] = read_win_type(buf, 'win:UInt64')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_21_payload(buf):
	ret = {}
	ret['Pages'] = read_win_type(buf, 'win:UInt64')
	ret['Objects'] = read_win_type(buf, 'win:UInt64')
	ret['IsLarge'] = read_win_type(buf, 'win:UInt32')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_22_payload(buf):
	ret = {}
	ret['Min'] = read_win_type(buf, 'win:UInt64')
	ret['Max'] = read_win_type(buf, 'win:UInt64')
	ret['Objects'] = read_win_type(buf, 'win:UInt64')
	ret['IsLarge'] = read_win_type(buf, 'win:UInt32')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_23_payload(buf):
	ret = {}
	ret['Reason'] = read_win_type(buf, 'win:UInt32')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_24_payload(buf):
	ret = {}
	ret['Reason'] = read_win_type(buf, 'win:UInt32')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_25_payload(buf):
	ret = {}
	ret['GenNumber'] = read_win_type(buf, 'win:UInt32')
	ret['IsAlloc'] = read_win_type(buf, 'win:UInt32')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_80_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_81_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_82_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_83_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_84_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_85_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_86_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_87_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_88_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_89_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_90_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_91_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_92_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_93_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_94_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_95_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_96_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_97_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_98_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_99_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_100_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_101_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_102_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_103_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_104_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_105_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_106_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_107_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_108_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_109_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_110_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_111_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_112_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_113_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_114_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_115_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_116_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_117_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_118_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_119_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_120_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_121_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_122_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_123_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_151_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')
	ret['Reserved1'] = read_win_type(buf, 'win:UInt8')
	ret['Reserved2'] = read_win_type(buf, 'win:UInt8')
	ret['FrameCount'] = read_win_type(buf, 'win:UInt32')
	ret['Stack'] = read_win_type(buf, 'win:Pointer')

def read_Microsoft_Windows_DotNETRuntimePrivate_158_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')
	ret['ModuleID'] = read_win_type(buf, 'win:UInt64')
	ret['RangeBegin'] = read_win_type(buf, 'win:UInt32')
	ret['RangeSize'] = read_win_type(buf, 'win:UInt32')
	ret['RangeType'] = read_win_type(buf, 'win:UInt8')
	ret['IBCType'] = read_win_type(buf, 'win:UInt8')
	ret['SectionType'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_159_payload(buf):
	ret = {}
	ret['AppDomainID'] = read_win_type(buf, 'win:UInt32')
	ret['LoadContextID'] = read_win_type(buf, 'win:UInt32')
	ret['FromLoaderCache'] = read_win_type(buf, 'win:UInt32')
	ret['DynamicLoad'] = read_win_type(buf, 'win:UInt32')
	ret['AssemblyCodebase'] = read_win_type(buf, 'win:UnicodeString')
	ret['AssemblyName'] = read_win_type(buf, 'win:UnicodeString')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_160_payload(buf):
	ret = {}
	ret['AppDomainID'] = read_win_type(buf, 'win:UInt32')
	ret['LoadContextID'] = read_win_type(buf, 'win:UInt32')
	ret['FromLoaderCache'] = read_win_type(buf, 'win:UInt32')
	ret['DynamicLoad'] = read_win_type(buf, 'win:UInt32')
	ret['AssemblyCodebase'] = read_win_type(buf, 'win:UnicodeString')
	ret['AssemblyName'] = read_win_type(buf, 'win:UnicodeString')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_161_payload(buf):
	ret = {}
	ret['AppDomainID'] = read_win_type(buf, 'win:UInt32')
	ret['LoadContextID'] = read_win_type(buf, 'win:UInt32')
	ret['FromLoaderCache'] = read_win_type(buf, 'win:UInt32')
	ret['DynamicLoad'] = read_win_type(buf, 'win:UInt32')
	ret['AssemblyCodebase'] = read_win_type(buf, 'win:UnicodeString')
	ret['AssemblyName'] = read_win_type(buf, 'win:UnicodeString')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_162_payload(buf):
	ret = {}
	ret['AppDomainID'] = read_win_type(buf, 'win:UInt32')
	ret['LoadContextID'] = read_win_type(buf, 'win:UInt32')
	ret['FromLoaderCache'] = read_win_type(buf, 'win:UInt32')
	ret['DynamicLoad'] = read_win_type(buf, 'win:UInt32')
	ret['AssemblyCodebase'] = read_win_type(buf, 'win:UnicodeString')
	ret['AssemblyName'] = read_win_type(buf, 'win:UnicodeString')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_163_payload(buf):
	ret = {}
	ret['AppDomainID'] = read_win_type(buf, 'win:UInt32')
	ret['LoadContextID'] = read_win_type(buf, 'win:UInt32')
	ret['FromLoaderCache'] = read_win_type(buf, 'win:UInt32')
	ret['DynamicLoad'] = read_win_type(buf, 'win:UInt32')
	ret['AssemblyCodebase'] = read_win_type(buf, 'win:UnicodeString')
	ret['AssemblyName'] = read_win_type(buf, 'win:UnicodeString')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_164_payload(buf):
	ret = {}
	ret['AppDomainID'] = read_win_type(buf, 'win:UInt32')
	ret['LoadContextID'] = read_win_type(buf, 'win:UInt32')
	ret['FromLoaderCache'] = read_win_type(buf, 'win:UInt32')
	ret['DynamicLoad'] = read_win_type(buf, 'win:UInt32')
	ret['AssemblyCodebase'] = read_win_type(buf, 'win:UnicodeString')
	ret['AssemblyName'] = read_win_type(buf, 'win:UnicodeString')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_165_payload(buf):
	ret = {}
	ret['AppDomainID'] = read_win_type(buf, 'win:UInt32')
	ret['LoadContextID'] = read_win_type(buf, 'win:UInt32')
	ret['FromLoaderCache'] = read_win_type(buf, 'win:UInt32')
	ret['DynamicLoad'] = read_win_type(buf, 'win:UInt32')
	ret['AssemblyCodebase'] = read_win_type(buf, 'win:UnicodeString')
	ret['AssemblyName'] = read_win_type(buf, 'win:UnicodeString')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_166_payload(buf):
	ret = {}
	ret['AppDomainID'] = read_win_type(buf, 'win:UInt32')
	ret['LoadContextID'] = read_win_type(buf, 'win:UInt32')
	ret['FromLoaderCache'] = read_win_type(buf, 'win:UInt32')
	ret['DynamicLoad'] = read_win_type(buf, 'win:UInt32')
	ret['AssemblyCodebase'] = read_win_type(buf, 'win:UnicodeString')
	ret['AssemblyName'] = read_win_type(buf, 'win:UnicodeString')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_167_payload(buf):
	ret = {}
	ret['AppDomainID'] = read_win_type(buf, 'win:UInt32')
	ret['LoadContextID'] = read_win_type(buf, 'win:UInt32')
	ret['FromLoaderCache'] = read_win_type(buf, 'win:UInt32')
	ret['DynamicLoad'] = read_win_type(buf, 'win:UInt32')
	ret['AssemblyCodebase'] = read_win_type(buf, 'win:UnicodeString')
	ret['AssemblyName'] = read_win_type(buf, 'win:UnicodeString')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_168_payload(buf):
	ret = {}
	ret['AppDomainID'] = read_win_type(buf, 'win:UInt32')
	ret['LoadContextID'] = read_win_type(buf, 'win:UInt32')
	ret['FromLoaderCache'] = read_win_type(buf, 'win:UInt32')
	ret['DynamicLoad'] = read_win_type(buf, 'win:UInt32')
	ret['AssemblyCodebase'] = read_win_type(buf, 'win:UnicodeString')
	ret['AssemblyName'] = read_win_type(buf, 'win:UnicodeString')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_169_payload(buf):
	ret = {}
	ret['AppDomainID'] = read_win_type(buf, 'win:UInt32')
	ret['LoadContextID'] = read_win_type(buf, 'win:UInt32')
	ret['FromLoaderCache'] = read_win_type(buf, 'win:UInt32')
	ret['DynamicLoad'] = read_win_type(buf, 'win:UInt32')
	ret['AssemblyCodebase'] = read_win_type(buf, 'win:UnicodeString')
	ret['AssemblyName'] = read_win_type(buf, 'win:UnicodeString')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_170_payload(buf):
	ret = {}
	ret['AppDomainID'] = read_win_type(buf, 'win:UInt32')
	ret['LoadContextID'] = read_win_type(buf, 'win:UInt32')
	ret['FromLoaderCache'] = read_win_type(buf, 'win:UInt32')
	ret['DynamicLoad'] = read_win_type(buf, 'win:UInt32')
	ret['AssemblyCodebase'] = read_win_type(buf, 'win:UnicodeString')
	ret['AssemblyName'] = read_win_type(buf, 'win:UnicodeString')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_171_payload(buf):
	ret = {}
	ret['AppDomainID'] = read_win_type(buf, 'win:UInt32')
	ret['LoadContextID'] = read_win_type(buf, 'win:UInt32')
	ret['FromLoaderCache'] = read_win_type(buf, 'win:UInt32')
	ret['DynamicLoad'] = read_win_type(buf, 'win:UInt32')
	ret['AssemblyCodebase'] = read_win_type(buf, 'win:UnicodeString')
	ret['AssemblyName'] = read_win_type(buf, 'win:UnicodeString')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_172_payload(buf):
	ret = {}
	ret['AppDomainID'] = read_win_type(buf, 'win:UInt32')
	ret['LoadContextID'] = read_win_type(buf, 'win:UInt32')
	ret['FromLoaderCache'] = read_win_type(buf, 'win:UInt32')
	ret['DynamicLoad'] = read_win_type(buf, 'win:UInt32')
	ret['AssemblyCodebase'] = read_win_type(buf, 'win:UnicodeString')
	ret['AssemblyName'] = read_win_type(buf, 'win:UnicodeString')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_173_payload(buf):
	ret = {}
	ret['AppDomainID'] = read_win_type(buf, 'win:UInt32')
	ret['LoadContextID'] = read_win_type(buf, 'win:UInt32')
	ret['FromLoaderCache'] = read_win_type(buf, 'win:UInt32')
	ret['DynamicLoad'] = read_win_type(buf, 'win:UInt32')
	ret['AssemblyCodebase'] = read_win_type(buf, 'win:UnicodeString')
	ret['AssemblyName'] = read_win_type(buf, 'win:UnicodeString')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_174_payload(buf):
	ret = {}
	ret['AppDomainID'] = read_win_type(buf, 'win:UInt32')
	ret['LoadContextID'] = read_win_type(buf, 'win:UInt32')
	ret['FromLoaderCache'] = read_win_type(buf, 'win:UInt32')
	ret['DynamicLoad'] = read_win_type(buf, 'win:UInt32')
	ret['AssemblyCodebase'] = read_win_type(buf, 'win:UnicodeString')
	ret['AssemblyName'] = read_win_type(buf, 'win:UnicodeString')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_175_payload(buf):
	ret = {}
	ret['AppDomainID'] = read_win_type(buf, 'win:UInt32')
	ret['LoadContextID'] = read_win_type(buf, 'win:UInt32')
	ret['FromLoaderCache'] = read_win_type(buf, 'win:UInt32')
	ret['DynamicLoad'] = read_win_type(buf, 'win:UInt32')
	ret['AssemblyCodebase'] = read_win_type(buf, 'win:UnicodeString')
	ret['AssemblyName'] = read_win_type(buf, 'win:UnicodeString')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_176_payload(buf):
	ret = {}
	ret['AppDomainID'] = read_win_type(buf, 'win:UInt32')
	ret['LoadContextID'] = read_win_type(buf, 'win:UInt32')
	ret['FromLoaderCache'] = read_win_type(buf, 'win:UInt32')
	ret['DynamicLoad'] = read_win_type(buf, 'win:UInt32')
	ret['AssemblyCodebase'] = read_win_type(buf, 'win:UnicodeString')
	ret['AssemblyName'] = read_win_type(buf, 'win:UnicodeString')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_177_payload(buf):
	ret = {}
	ret['Type'] = read_win_type(buf, 'win:UInt32')
	ret['AppDomain'] = read_win_type(buf, 'win:UInt32')
	ret['ILImage'] = read_win_type(buf, 'win:UnicodeString')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_178_payload(buf):
	ret = {}
	ret['Module'] = read_win_type(buf, 'win:UnicodeString')
	ret['AppDomainID'] = read_win_type(buf, 'win:UInt32')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_179_payload(buf):
	ret = {}
	ret['Module'] = read_win_type(buf, 'win:UnicodeString')
	ret['AppDomainID'] = read_win_type(buf, 'win:UInt32')
	ret['IsAllCritical'] = read_win_type(buf, 'win:Boolean')
	ret['IsAllTransparent'] = read_win_type(buf, 'win:Boolean')
	ret['IsTreatAsSafe'] = read_win_type(buf, 'win:Boolean')
	ret['IsOpportunisticallyCritical'] = read_win_type(buf, 'win:Boolean')
	ret['SecurityRuleSet'] = read_win_type(buf, 'win:UInt32')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_180_payload(buf):
	ret = {}
	ret['Type'] = read_win_type(buf, 'win:UnicodeString')
	ret['Module'] = read_win_type(buf, 'win:UnicodeString')
	ret['AppDomainID'] = read_win_type(buf, 'win:UInt32')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_181_payload(buf):
	ret = {}
	ret['Type'] = read_win_type(buf, 'win:UnicodeString')
	ret['Module'] = read_win_type(buf, 'win:UnicodeString')
	ret['AppDomainID'] = read_win_type(buf, 'win:UInt32')
	ret['IsAllCritical'] = read_win_type(buf, 'win:Boolean')
	ret['IsAllTransparent'] = read_win_type(buf, 'win:Boolean')
	ret['IsCritical'] = read_win_type(buf, 'win:Boolean')
	ret['IsTreatAsSafe'] = read_win_type(buf, 'win:Boolean')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_182_payload(buf):
	ret = {}
	ret['Method'] = read_win_type(buf, 'win:UnicodeString')
	ret['Module'] = read_win_type(buf, 'win:UnicodeString')
	ret['AppDomainID'] = read_win_type(buf, 'win:UInt32')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_183_payload(buf):
	ret = {}
	ret['Method'] = read_win_type(buf, 'win:UnicodeString')
	ret['Module'] = read_win_type(buf, 'win:UnicodeString')
	ret['AppDomainID'] = read_win_type(buf, 'win:UInt32')
	ret['IsCritical'] = read_win_type(buf, 'win:Boolean')
	ret['IsTreatAsSafe'] = read_win_type(buf, 'win:Boolean')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_184_payload(buf):
	ret = {}
	ret['Field'] = read_win_type(buf, 'win:UnicodeString')
	ret['Module'] = read_win_type(buf, 'win:UnicodeString')
	ret['AppDomainID'] = read_win_type(buf, 'win:UInt32')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_185_payload(buf):
	ret = {}
	ret['Field'] = read_win_type(buf, 'win:UnicodeString')
	ret['Module'] = read_win_type(buf, 'win:UnicodeString')
	ret['AppDomainID'] = read_win_type(buf, 'win:UInt32')
	ret['IsCritical'] = read_win_type(buf, 'win:Boolean')
	ret['IsTreatAsSafe'] = read_win_type(buf, 'win:Boolean')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_186_payload(buf):
	ret = {}
	ret['Token'] = read_win_type(buf, 'win:UInt32')
	ret['Module'] = read_win_type(buf, 'win:UnicodeString')
	ret['AppDomainID'] = read_win_type(buf, 'win:UInt32')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_187_payload(buf):
	ret = {}
	ret['Token'] = read_win_type(buf, 'win:UInt32')
	ret['Module'] = read_win_type(buf, 'win:UnicodeString')
	ret['AppDomainID'] = read_win_type(buf, 'win:UInt32')
	ret['IsCritical'] = read_win_type(buf, 'win:Boolean')
	ret['IsTreatAsSafe'] = read_win_type(buf, 'win:Boolean')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_188_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')
	ret['BindingID'] = read_win_type(buf, 'win:UInt64')
	ret['ReasonCode'] = read_win_type(buf, 'win:UInt32')
	ret['AssemblyName'] = read_win_type(buf, 'win:UnicodeString')

def read_Microsoft_Windows_DotNETRuntimePrivate_191_payload(buf):
	ret = {}
	ret['FailFastUserMessage'] = read_win_type(buf, 'win:UnicodeString')
	ret['FailedEIP'] = read_win_type(buf, 'win:Pointer')
	ret['OSExitCode'] = read_win_type(buf, 'win:UInt32')
	ret['ClrExitCode'] = read_win_type(buf, 'win:UInt32')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_192_payload(buf):
	ret = {}
	ret['TypeID'] = read_win_type(buf, 'win:Pointer')
	ret['ObjectID'] = read_win_type(buf, 'win:Pointer')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')
	ret['TypeName'] = read_win_type(buf, 'win:UnicodeString')

def read_Microsoft_Windows_DotNETRuntimePrivate_193_payload(buf):
	ret = {}
	ret['HandleID'] = read_win_type(buf, 'win:Pointer')
	ret['ObjectID'] = read_win_type(buf, 'win:Pointer')
	ret['COMInterfacePointer'] = read_win_type(buf, 'win:Pointer')
	ret['NewRefCount'] = read_win_type(buf, 'win:UInt32')
	ret['AppDomainID'] = read_win_type(buf, 'win:UInt64')
	ret['ClassName'] = read_win_type(buf, 'win:AnsiString')
	ret['NameSpace'] = read_win_type(buf, 'win:AnsiString')
	ret['Operation'] = read_win_type(buf, 'win:UnicodeString')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_194_payload(buf):
	ret = {}
	ret['HandleID'] = read_win_type(buf, 'win:Pointer')
	ret['ObjectID'] = read_win_type(buf, 'win:Pointer')
	ret['Kind'] = read_win_type(buf, 'win:UInt32')
	ret['Generation'] = read_win_type(buf, 'win:UInt32')
	ret['AppDomainID'] = read_win_type(buf, 'win:UInt64')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_195_payload(buf):
	ret = {}
	ret['HandleID'] = read_win_type(buf, 'win:Pointer')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_196_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')
	ret['Prepend'] = read_win_type(buf, 'win:Boolean')
	ret['Message'] = read_win_type(buf, 'win:UnicodeString')

def read_Microsoft_Windows_DotNETRuntimePrivate_197_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')
	ret['Category'] = read_win_type(buf, 'win:UInt32')
	ret['ErrorCode'] = read_win_type(buf, 'win:UInt32')

def read_Microsoft_Windows_DotNETRuntimePrivate_199_payload(buf):
	ret = {}
	ret['PlugStart'] = read_win_type(buf, 'win:Pointer')
	ret['PlugEnd'] = read_win_type(buf, 'win:Pointer')
	ret['GapBeforeSize'] = read_win_type(buf, 'win:Pointer')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_310_payload(buf):
	ret = {}
	ret['LoaderHeapPtr'] = read_win_type(buf, 'win:Pointer')
	ret['MemoryAddress'] = read_win_type(buf, 'win:Pointer')
	ret['RequestSize'] = read_win_type(buf, 'win:UInt32')
	ret['Unused1'] = read_win_type(buf, 'win:UInt32')
	ret['Unused2'] = read_win_type(buf, 'win:UInt64')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_201_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')
	ret['String1'] = read_win_type(buf, 'win:UnicodeString')
	ret['String2'] = read_win_type(buf, 'win:UnicodeString')
	ret['Int1'] = read_win_type(buf, 'win:Int32')
	ret['Int2'] = read_win_type(buf, 'win:Int32')
	ret['Int3'] = read_win_type(buf, 'win:Int32')

def read_Microsoft_Windows_DotNETRuntimePrivate_202_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')
	ret['ModuleID'] = read_win_type(buf, 'win:UInt64')
	ret['MethodID'] = read_win_type(buf, 'win:UInt64')

def read_Microsoft_Windows_DotNETRuntimePrivate_400_payload(buf):
	ret = {}
	ret['TypeName'] = read_win_type(buf, 'win:UnicodeString')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_401_payload(buf):
	ret = {}
	ret['TypeName'] = read_win_type(buf, 'win:UnicodeString')
	ret['SecondTypeName'] = read_win_type(buf, 'win:UnicodeString')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_402_payload(buf):
	ret = {}
	ret['TypeName'] = read_win_type(buf, 'win:UnicodeString')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_403_payload(buf):
	ret = {}
	ret['TypeName'] = read_win_type(buf, 'win:UnicodeString')
	ret['InterfaceTypeName'] = read_win_type(buf, 'win:UnicodeString')
	ret['VariantInterfaceTypeName'] = read_win_type(buf, 'win:UnicodeString')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_404_payload(buf):
	ret = {}
	ret['TypeName'] = read_win_type(buf, 'win:UnicodeString')
	ret['SecondTypeName'] = read_win_type(buf, 'win:UnicodeString')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_405_payload(buf):
	ret = {}
	ret['TypeName'] = read_win_type(buf, 'win:UnicodeString')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_406_payload(buf):
	ret = {}
	ret['TypeName'] = read_win_type(buf, 'win:UnicodeString')
	ret['InterfaceTypeName'] = read_win_type(buf, 'win:UnicodeString')
	ret['VariantInterfaceTypeName'] = read_win_type(buf, 'win:UnicodeString')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_407_payload(buf):
	ret = {}
	ret['TypeName'] = read_win_type(buf, 'win:UnicodeString')
	ret['Int1'] = read_win_type(buf, 'win:Int32')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_408_payload(buf):
	ret = {}
	ret['TypeName'] = read_win_type(buf, 'win:UnicodeString')
	ret['SecondTypeName'] = read_win_type(buf, 'win:UnicodeString')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_409_payload(buf):
	ret = {}
	ret['TypeName'] = read_win_type(buf, 'win:UnicodeString')
	ret['SecondTypeName'] = read_win_type(buf, 'win:UnicodeString')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_410_payload(buf):
	ret = {}
	ret['TypeName'] = read_win_type(buf, 'win:UnicodeString')
	ret['SecondTypeName'] = read_win_type(buf, 'win:UnicodeString')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_411_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_412_payload(buf):
	ret = {}
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

def read_Microsoft_Windows_DotNETRuntimePrivate_413_payload(buf):
	ret = {}
	ret['TypeName'] = read_win_type(buf, 'win:UnicodeString')
	ret['Int1'] = read_win_type(buf, 'win:Int32')
	ret['ClrInstanceID'] = read_win_type(buf, 'win:UInt16')

